Header component
Snoopyk8411/nbbp-fe pull request #10
Opened 2021-11-30 06:40 UTC by GlebShulga

2021-11-30 11:28 UTC, Snoopyk8411 requested changes

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header/header.module.css
> +    background: var(--black) !important;
зачем импортанты?

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header/header.module.css
> +    display: none !important;
какой то перебор явно

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header/header.module.css
> +  box-shadow: 0 1px 17px rgb(0 0 0 / 9%); /* приём взял у Вкусвилла */
ну так погугли как он работает)

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header/header.tsx
> +              placeholder='начните поиск'
в константы бы все магические тексты

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header_bottom_menu/Menu.tsx
> +// компонент на период разаработки.
ничего не понял
1) комментарии должны быть на английском
2) они должны быть по делу и с заведенными задачами

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header_bottom_menu/Menu.tsx
> +// компонент на период разаработки.
уже обсуждали же

2021-11-30 11:28 UTC, Snoopyk8411 commented on src/components/header_bottom_menu/menu.module.css
> +Когда появятся отдельные компонеты Каталог, Вакансии, Доставка и т. д. перенесу логику этого компонента в Header. */
тож самое - нет задачи, не по шаблону, не на английском

2021-11-30 11:43 UTC, GlebShulga commented on src/components/header/header.module.css
> +    background: var(--black) !important;
Изменение цветов при изменении темы со светлой на темную без !important работать отказывается.

2021-11-30 11:46 UTC, GlebShulga commented on src/components/header/header.module.css
> +    display: none !important;
Была задумка, что на мобилках строка поиска исчерает и остается только кнопка. При нажатии на кнопку будет появляться модалка с полем для поиска. Всё как у Вкусвилла. Убрал импорт, здесь работает без него.

2021-11-30 12:00 UTC, GlebShulga commented on src/components/header_bottom_menu/Menu.tsx
> +// компонент на период разаработки.
Завел задачу в Jira, отметил, что она у меня в работе.

2021-11-30 12:00 UTC, GlebShulga commented on src/components/header_bottom_menu/menu.module.css
> +Когда появятся отдельные компонеты Каталог, Вакансии, Доставка и т. д. перенесу логику этого компонента в Header. */
Перевел комментарии.

2021-12-01 12:16 UTC, asnoskov commented on src/components/header/header.module.css
> +    background: var(--black) !important;
может быть специфичность селектора можно повысить (если другое правило !important не юзает конечно)?

2021-12-01 14:45 UTC, asnoskov requested changes

2021-12-01 14:45 UTC, asnoskov commented on src/components/header_bottom_menu/Menu.tsx
> +    <div aria-live='polite' id='menu' className={menuStyles.menu_row} role='group'>
По семантике лучше использовать nav вместо div для навигации

2021-12-02 06:47 UTC, GlebShulga commented on src/components/header_bottom_menu/Menu.tsx
> +    <div aria-live='polite' id='menu' className={menuStyles.menu_row} role='group'>
fixed

2021-12-02 14:09 UTC, GlebShulga commented on src/components/header/header.module.css
> +    background: var(--black) !important;
Убрал !important, перенес стили @media (prefers-color-scheme: dark) в конец файла.

2021-12-06 15:28 UTC, Snoopyk8411 approved these changes

2021-12-06 18:43 UTC, merged