Feature/nbpp 31 be search products
Snoopyk8411/nbbp-fe pull request #11
Opened 2021-11-30 14:03 UTC by Beljar

2021-12-01 15:15 UTC, GlebShulga requested changes

2021-12-01 15:15 UTC, GlebShulga commented on src/pages/api/search/index.ts
> +    let result: object[] = searchProduct(value, mockProducts, SEARCH_KEYS);
Думаю лучше использовать интерфейс IProduct вместо объекта.

2021-12-01 15:15 UTC, GlebShulga commented on src/pages/api/search/trimPunctuation.ts
> +  const re = RegExp(`^[${PUNCTUATION_CODES.join()}]*(.+?)[${PUNCTUATION_CODES.join()}]*$`, 'gmu');
Предлагаю упростить функцию до
 ```
export const trimPunctuation = (value: string): string => {
  const result = value.replace(/[\p{P}]/gmu, '')
  return result
};
```
Убирает все символы пунктуации по всей строке.

2021-12-01 15:15 UTC, GlebShulga commented on src/pages/api/search/searchProduct.ts
> +    console.log(shiftedString);
console.log нужно удалить

2021-12-01 16:01 UTC, Snoopyk8411 requested changes

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +    console.log(shiftedString);
консоль лог

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/constants.ts
> +export type SearchKeysType = keyof IProduct;
у нас соглашение, что все типы начинаются с заглавной I буквы

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/constants.ts
> +export type SearchKeysType = keyof IProduct;
и почему у тебя тип в константах? выноси его тогда в types.ts

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/index.ts
> +  if (typeof value === 'string') {
1) не очень понятно зачем здесь это условие - чем ещё может быть value?
2) у тебя получаются вложенные if'ы что не хорошо
проще и качественнее сделать тогда примерно таким образом
const isValueValid = typeof value === 'string';
if (isValueValid) {
res.status(400).end(WRONG_QUERY_ERROR);
return; // если он тут нужен - нужно почитать как работает end
}

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/index.ts
> +    if (Number(limit)) {
снова непонятное условие, да ещё и дублирование Number(limit)
1) ты можешь вместо const { value = '', limit } = req.query; использовать const { value = '', limit: limitParam } = req.query;
а затем const limit = Number.isNaN(Number(limitParam)) ? undefined : Number(limitParam);
и тогда этот if тебе тоже будет не нужен 

повторяю - в if мы стараемся использовать декларативные семантически верные флаги. В следующий раз повторять не буду, буду просто указывать

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/index.ts
> +const search = (req: NextApiRequest, res: NextApiResponse): void => {
почему просто search? это же не поиск в глобальном смысле - это вполне конкретный поиск. Мне кажется стоит переименовать во что-то более точно описывающее

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/mockProducts.ts
> +export interface IRating {
1) почему типы вместе с моками? 
2) у нас конкретное место есть для моков
3) мы договаривались что моки будут типизированы

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +export const searchProduct = (value: string, products: IProduct[], keys: SearchKeysType[]): IProduct[] => {
почему keys? ну так их и назови searchKeys, или searchChars

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +      const key = Array.isArray(path) ? path[0] : path;
снова - почему key? как связано с keys? почему берется из path? непонятно, надо более явно именовать переменные

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +      const key = Array.isArray(path) ? path[0] : path;
видимо это не key, а id

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +      if (typeof key === 'string') {
и снова вложенные if
1) мне искренне непонятно чем ещё может быть id - чем? зачем эта проверка?
но в любом случае стоит сделать так
let value = '';
const isIdValid = typeof id === 'string' // либо другая какая проверка
затем if (!isIdValid) return value;
2) далее
зачем if на 17-ой строчке мне тоже не понятно - от каких значений ограждаемся то?
предположу, что это число или строка или null или undefined, 
то все равно
value = product[id as keyof IProduct];
const isValueValid = !!value;
value = `${isValueValid ? value : ''}`.split(' ')
            .map(word => word.trim())
            .map(trimPunctuation);
return value;

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +  if (searchString.length === 0) {
1) const isEmptySearchString = searchString.length === 0;
2) if (isEmptySearchString) return products;
3) располагаться этот if явно должен перед const options, дабы всё находилось на своих местах и без дела не создавалось

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +  if (result.length === 0 && value.length > 1) {
мистическое условие - ни о чем не говорит, должно быть в декларативном флаге

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +    if (shiftedString !== value) {
лишнее условие - зачем оно? и зачем мы дважды делаем  .map(result => result.item) ?

я всё это условие не понимаю, честно говоря - почему нас интересует условие shiftedString !== value
если посмотреть выше

const shiftedString: string = shiftString(value);
const searchString = trimPunctuation(value.trim());
1) ну во первых, тогда наверно везде нужно прокидывать value.trim()
2) нужно не заново поиск делать, а, если это возможно, выбирать чем искать какой стрингой
3) убрать .map(result => result.item);

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/searchProduct.ts
> +  return result;
return result.map(result => result.item);

вот сюда перенести

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/trimPunctuation.ts
> +  const re = RegExp(`^[${PUNCTUATION_CODES.join()}]*(.+?)[${PUNCTUATION_CODES.join()}]*$`, 'gmu');
страшная регуляка - она должна быть присвоена не re, а переменной, из названия которой становится понятно что это за регулярка

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/trimPunctuation.ts
> +  const result = re.exec(value);
это не result в данном случае - result, это то что возвращается
в данном случае const parsedValues = something.exec(value)
а затем
const result = !!parsedValues && parsedValues.length > 1 ? (parsedValues[1] as string) : '';

2021-12-01 16:01 UTC, Snoopyk8411 commented on src/pages/api/search/trimPunctuation.ts
> +  return result && result.length > 1 ? (result[1] as string) : '';
что это за странное условие? почему нас интересует второй элемент выдачи?
мне кажется, это будет всё сильно очевиднее выглядеть, если будет сделано через деструктуризацию

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/searchProduct.ts
> +    if (shiftedString !== value) {
shiftedString !== value чтобы понимать, что строка изменилась в результате преобразования shiftString. shiftString работает так: каждый латинский символ или знак пунктуации, расположенный на буквенной клавише преобразует в русский символ. Но если в строке таких символов изначально не было, то никаких преобразований не будет. А если не было преобразований, то зачем делать лишний поиск?
По поводу выбирать, какой стрингой искать - это надо, наверное, словари подключать, не знаю вообще надо ли такое нам на фронтендовском проекте. Или я не знаю, как еще он может заранее понять, правильное ли слово введено или абра-кадабра с непереключенной клавиатуры.
По поводу того, зачем прокидывать trim() я не уловил. Наверное, надо на Q&A обсуждать.

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/index.ts
> +  if (typeof value === 'string') {
Условие изначально ввел для того, чтобы TS не ругался) Сейчас переделал на value as string.

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/mockProducts.ts
> +export interface IRating {
Вообще планировал моки продуктов и их типы взять из таска 28, но он не был готов, поэтому налепил как попало) Сейчас перенес.

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/searchProduct.ts
> +export const searchProduct = (value: string, products: IProduct[], keys: SearchKeysType[]): IProduct[] => {
Это поля объекта IProduct, по которым ведется поиск. Переименовал в searchKeys.

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/searchProduct.ts
> +      const key = Array.isArray(path) ? path[0] : path;
так работает колбек во fuse. Насколько я разобрался, path - это путь к нужному полю объекта, который представляется как список последовательных имен полей (которые keys). 
Т.е. например obj = {product: {name:abc}}, чтобы достучаться до name надо передать path = ["product", "name"]. 
В моем случае это всегда будет одно поле с именем "title", т.к. мы ищем только по нему. В path оно падает в виде ["title"], соответсвенно мне надо его оттуда достать и это будет key. Наименования брал из доков по Fuse. Поиск идет по массиву объектов, key - это имя поля объекта. Поменял на searchKey.

2021-12-03 15:15 UTC, Beljar commented on src/pages/api/search/searchProduct.ts
> +      if (typeof key === 'string') {
Все эти злобные проверки нужны, чтобы не было ошибок typescript'a, он же думает, что мы обращаемся к какому-то рандомному полю объекта и не знает, что там лежит. Если просто проверить, что не null и не undefined, то он все-равно подсветит метод split как ошибочный. Переделал без if'ов.

2021-12-04 00:14 UTC, Beljar commented on src/pages/api/search/searchProduct.ts
> +    if (shiftedString !== value) {
trim в результате прокинул после проверки, что shiftedString !== value

2021-12-06 07:35 UTC, GlebShulga approved these changes

2021-12-06 07:35 UTC, GlebShulga commented on src/pages/api/search/search.test.ts
> +  {
можно импортировать этот массив с mock-data/product-data.ts и не дублировать данные.

2021-12-06 14:46 UTC, Snoopyk8411 approved these changes

2021-12-07 08:35 UTC, Beljar commented on src/pages/api/search/search.test.ts
> +  {
Не, так не надо. В mock-data/product-data.ts массив можем добавлять, менять при мержах и т.п. Тогда тесты будут падать. Пусть в тестах останется независимый массив.

2021-12-07 08:35 UTC, merged