Feature/nbpp 18 menu
Snoopyk8411/nbbp-fe pull request #12
Opened 2021-12-01 12:10 UTC by asnoskov

2021-12-02 07:42 UTC, py-cs requested changes

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +import menuStyles from './menu.module.css';
Порядок импортов по стайлгайду - относительный импорт в конец списка

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +}: IMenuLevelProps) => {
Дублирование, тип пропсов уже в дженерике

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  const [wrapperClassName, setWrapperClassName] = useState(closedWrapperClassName);
useState может иметь только два значения, может сделать boolean?
а на стр. 83 через classnames навешать классы, тогда константы на стр. 50 и 51 тоже будут не нужны

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +    (submenuOpenActionType === SubmenuOpenActionType.Hover && setOpenedSubmenuId(itemId)) as void;
Наверное лучше написать через If, чтобы избавиться от кастинга типов.

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  const handleWrapperTransitionEnd = (): void => (isClosing && onClose && onClose()) as void;
Тоже через If

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  if (!containerElement || !sortedItems) {
Вынести в отдельный флаг, например shouldRender = containerElement && sortedItems.length

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  const showBackToParentLink = submenuPosition === SubmenuPosition.Overlap;
нейминг флага (с is, should, has, ...)

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +              className={getMenuItemClass(!!item.children && item.children.length > 0)}
можно просто item.children.length, т.к. всё, что больше 0  == true.
вынести в отдельный флаг.

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +            {item.children && item.children.length > 0 && item.id === openedSubmenuId && (
аналогично стр. 93

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  const menuContainerRef = useRef(null as HTMLDivElement | null);
useRef<HTMLDivElement | null>(null)

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +  const [containerElement, setContainerElement] = useState<HTMLElement | null>(null);
```
дублирование, можно сделать тип Nullable<T> = T || null
и использовать Nullable<HTMLElement>
```

2021-12-02 07:42 UTC, py-cs commented on src/components/menu/menu.tsx
> +    return 0;
(a, b) => b.order - a.order

2021-12-02 07:42 UTC, py-cs commented on src/components/popup/popup.tsx
> +    (hideActionType === HideActionType.ClickOutside && setIsVisible(false)) as void;
Через If?

2021-12-02 07:42 UTC, py-cs commented on src/components/popup/popup.tsx
> +  const handleMouseLeave = (): void => (hideActionType === HideActionType.MouseOut && setIsVisible(false)) as void;
аналогично

2021-12-06 15:22 UTC, Snoopyk8411 requested changes

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +import menuStyles from './menu.module.css';
согласен

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +export enum SubmenuOpenActionType {
интерфейсы и енамки стоит хранить в отдельных файлах. Енамки в constants.ts, видимо, а типы и интерфейсы в interfaces.ts в соседнем файле

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +const getMenuContainerClass = (submenuPosition: SubmenuPosition): string | undefined =>
а такие утилиты стоит держать тоже в отдельном файле - utils.ts

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +    setContainerElement(menuContainerRef.current);
зачем тебе все время обновлять рефу?

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +    setContainerElement(menuContainerRef.current);
может тебе тогда посмотреть в сторону классового компонента??

см - https://ru.reactjs.org/docs/refs-and-the-dom.html

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +  const [containerElement, setContainerElement] = useState<HTMLElement | null>(null);
кажется это делается через forwardRef

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +            {item.children && item.children.length > 0 && item.id === openedSubmenuId && (
это условие стоит вынести в отдельный флаг константу и назвать её декларативно типо isSubmenuOpened, или как тут корректнее будет

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +const getMenuLevelClass = (isRoot: boolean): string | undefined =>
к тому же, использовать функции до их определения как то не оч хорошо

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +const getMenuLevelClass = (isRoot: boolean): string | undefined =>
и как это они у тебя могут undefined вернуть?

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +              className={getMenuItemClass(!!item.children && item.children.length > 0)}
вообще хороший тон делать не совсем так, а примерно 

{sortedItems.map(item => {
const { id, name, url, children } = item; // деструктурирование опционально, естественно, но кажется так лаконичнее
const isItemWithChildren = !!children && children.length > 0;
const menuItemClassName = getMenuItemClass(isItemWithChildren);
const isSubmenuOpened = isItemWithChildren && id === openedSubmenuId; // или как корректнее назвать этот флаг
return ( ...

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +          <li className={`${menuStyles.menu_item} ${menuStyles.menu_item_back_to_parent}`} onClick={handleCloseClick}>
а почему бы не деструктурировать styles??

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +  useEffect(() => {
тут бы комментарий оставить зачем такой интересный эффект

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +    setIsClosing(true);
видимо setIsClosing(false) не нужен, так как компонент анмаунтиться?

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +  const openedWrapperClassName = `${menuStyles.menu_level_wrapper} ${menuStyles.opened}`;
можно вообще classnames использовать для динамического тугла opened класса

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +  const triggerClosingAnimation = (): void => setWrapperClassName(closedWrapperClassName);
у тебя же нет класса closed или closing, по сути ты делаешь toggle класса opened

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/menu/menu.tsx
> +  const sortedItems = useMemo(() => getSortedItems(items), [items]);
точно useMemo а не useCallback тебе нужно?

2021-12-06 15:22 UTC, Snoopyk8411 commented on src/components/popup/popup.tsx
> +// eslint-disable-next-line react/prop-types
это зачем?)

2021-12-06 23:13 UTC, asnoskov commented on src/components/menu/menu.tsx
> +    (submenuOpenActionType === SubmenuOpenActionType.Hover && setOpenedSubmenuId(itemId)) as void;
обернул тело лямбды в блок кода {}, чтобы избавиться от кастинга.

2021-12-06 23:13 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const handleWrapperTransitionEnd = (): void => (isClosing && onClose && onClose()) as void;
обернул в {}, чтобы убрать implicit return

2021-12-06 23:53 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const sortedItems = useMemo(() => getSortedItems(items), [items]);
Я делаю сортировку пунктов меню по order один раз и использую результат при последующих рендерах пока не придут новые menu items в props. Поэтому использовал useMemo, чтобы закэшировать результат.

2021-12-07 00:46 UTC, asnoskov commented on src/components/menu/menu.tsx
> +}: IMenuLevelProps) => {
Попробовал убрать, но вылезает missing in props validation error у ESLint. Но вообще, честно говоря, не думаю, что здесь дублирование - большая проблема, т.к. Typescript всё равно не позволит указать разные типы здесь и в аргументе generic'а, а значит два дубликата не могут стать несогласованными со временем. Да, из минусов многословность, но из плюсов - чуть лучше читаемость кода, т.к. видно какой у метода результат, не проваливаясь в generic (в языках вроде java или c# в принципе нельзя опустить тип в этом случае). В целом я вроде и не за и не против (хотя после C# мне указывать тип чуть привычнее), но из за линтера оставил как есть.

2021-12-07 01:06 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const triggerClosingAnimation = (): void => setWrapperClassName(closedWrapperClassName);
Да, у меня есть два класса opened и closed и есть css transition для изменяемых свойств, за счет которого срабатывает анимация. Соответственно, чтобы дернуть анимацию мне нужно применить тот или иной класс, но из кода не понятно, что классы я применяю для запуска анимации. Я бы мог добавить комментарии вроде "this is for triggering animation", но решил обернуть в методы соответствующими названиями, чтобы сделать код самодокументируемым.

2021-12-07 15:25 UTC, asnoskov commented on src/components/menu/menu.tsx
> +import menuStyles from './menu.module.css';
поправил

2021-12-07 15:27 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const [wrapperClassName, setWrapperClassName] = useState(closedWrapperClassName);
поменял на boolean, заюзал classnames

2021-12-07 15:29 UTC, asnoskov commented on src/components/menu/menu.tsx
> +export enum SubmenuOpenActionType {
вынес в constains и interfaces

2021-12-07 15:29 UTC, asnoskov commented on src/components/menu/menu.tsx
> +const getMenuContainerClass = (submenuPosition: SubmenuPosition): string | undefined =>
вынес в utils

2021-12-07 15:41 UTC, asnoskov commented on src/components/menu/menu.tsx
> +    setIsClosing(true);
Это флаг, что компонент в процессе закрытия (но анимация еще не закончилась). В компоненте есть подписка на transitionEnd (конец анимации), в ней мы по этому флагу понимаем, что закончившаяся именно анимация закрытия (а не открытия) и тогда триггерим onClose, а по этому событию уже компонент анмаунтится. Сейчас убрал этот флаг, использовал isOpened - флаг, навешивающий класс полностью открытого меню. Когда меняем значение флага, триггерится анимация открытия/закрытия. А в handleTransitionEnd по значению isOpened можем узнать какая именно анимация закончилась, чтобы в случае закрытия выбросить onClose.

2021-12-07 15:42 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const openedWrapperClassName = `${menuStyles.menu_level_wrapper} ${menuStyles.opened}`;
Использовал classnames

2021-12-07 15:48 UTC, asnoskov commented on src/components/popup/popup.tsx
> +// eslint-disable-next-line react/prop-types
поправил

2021-12-07 17:23 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const [containerElement, setContainerElement] = useState<HTMLElement | null>(null);
переделал на callback ref

2021-12-07 17:24 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  const [containerElement, setContainerElement] = useState<HTMLElement | null>(null);
> 

точно ли стоит выносить Nullable<T>? что мы выигрываем от этого?

2021-12-07 17:30 UTC, asnoskov commented on src/components/menu/menu.tsx
> +    setContainerElement(menuContainerRef.current);
переделал на callback ref

2021-12-07 17:47 UTC, asnoskov commented on src/components/menu/menu.tsx
> +              className={getMenuItemClass(!!item.children && item.children.length > 0)}
поправил

2021-12-07 17:57 UTC, asnoskov commented on src/components/menu/menu.tsx
> +          <li className={`${menuStyles.menu_item} ${menuStyles.menu_item_back_to_parent}`} onClick={handleCloseClick}>
Меня смущает, что они потенциально могут конфликтовать по семантике с каким-нибудь другим menuItem, и что названия не будут отражать, что это имена css классов т.к. лишатся контекста. а так можно вместо условного menu_item_class_name написать menuStyles.menu_item. Короче, пока не трогал, давайте обсудим. Хотя menuStyles, мне кажется, можно переименовать на styles, т.к. контекст понятен?

2021-12-07 18:25 UTC, asnoskov commented on src/components/menu/menu.tsx
> +  useEffect(() => {
перенес в triggerOpeningAnimation() метод, т.к. деталь имплементации, добавил комментарий в нем

2021-12-07 18:30 UTC, asnoskov commented on src/components/menu/menu.tsx
> +const getMenuLevelClass = (isRoot: boolean): string | undefined =>
да, убрал undefined. функции вынес в utils

2021-12-07 18:37 UTC, asnoskov commented on src/components/menu/menu.tsx
> +              className={getMenuItemClass(!!item.children && item.children.length > 0)}
единственное тут дополнительную проверку на children пришлось оставить, иначе typescript ругается, думает, что children могут быть undefined (хоть это и исключено по коду), тогда как items - не могут:
:{children && isSubmenuOpened && (
                <MenuLevel
                ...
                items={children}

2021-12-08 05:47 UTC, py-cs approved these changes

2021-12-08 11:49 UTC, Snoopyk8411 approved these changes

2021-12-08 11:53 UTC, merged