Feature/nbpp 23 breadcrumbs component
Snoopyk8411/nbbp-fe pull request #14
Opened 2021-12-08 08:49 UTC by Beljar

2021-12-08 11:58 UTC, py-cs approved these changes

2021-12-08 12:04 UTC, Snoopyk8411 requested changes

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/index.tsx
> +export * from './Breadcrumbs';
договаривались же не один раз - мы не используем wildcard

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/index.tsx
> +export * from './Breadcrumbs';
зачем он тут?

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +          const isLast = idx === path.length - 1;
isLastСrumb - я думаю будет норм компромиссом

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +        {path.map((breadcrumb, idx) => {
не idx, а index

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +const drawBreadcrump = (breadcrumb: IBreadcrumb, isCurrent?: boolean): JSX.Element => {
1) drawBreadcrump - орфография
2) isCurrent - что за current? ниже у тебя isLastCrumb - нужно использовать одинаковые имена для одинаковых сущностей

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/link/Link.tsx
> +  areaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'false' | 'true';
вынести в enum в константы надо бы

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +const drawBreadcrump = (breadcrumb: IBreadcrumb, isCurrent?: boolean): JSX.Element => {
3) и тогда уж не draw, а getBreadcrumb
4) или вообще сделать компонентом <Breadcrumb /> - этот вариант предпочтительнее

2021-12-08 12:04 UTC, Snoopyk8411 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  if (breadcrumb.url) {
if (breadcrumb.url) { - совершенно не содержательная строчка, абсолютно непонятно о чем она говорит

почему мы такое условие ставим? потому что без урла - не кликабельна крамба
следовательно, условие должно звучать так

const isBreadcrumbClickable = !!breadcrumb.url;
if (isBreadcrumbClickable) { ...

или типо того

2021-12-08 21:51 UTC, Beljar commented on src/components/Breadcrumbs/index.tsx
> +export * from './Breadcrumbs';
привычка-с

2021-12-09 11:22 UTC, Snoopyk8411 approved these changes

2021-12-09 11:23 UTC, merged