Feature/nbpp 20 fe search component
Snoopyk8411/nbbp-fe pull request #17
Opened 2021-12-10 10:04 UTC by GlebShulga

2021-12-10 14:45 UTC, Beljar commented on src/components/search/input/Input.tsx
> +        const res = await axios.get(SEARCH_API);
обычно общение с серваком выносится в отдельные файлы.
сам axios, насколько я знаю, может пульнуть ошибку, поэтому стоит не только респонс проверять, но и весь вызов оборачивать в try catch.

2021-12-10 14:45 UTC, Beljar commented on src/components/search/input/Input.tsx
> +  const debouncedValue = useDebounce(searchValue, 500);
magic number

2021-12-10 14:45 UTC, Beljar commented on src/components/search/input/Input.tsx
> +        if (res.status !== 200) {
magic number

2021-12-10 14:45 UTC, Beljar commented on src/components/search/input/Input.tsx
> +    const res = event.target.value;
я бы делал
const {target: {value = ''}} = event | {}

2021-12-10 14:45 UTC, Beljar commented on src/components/search/input/Input.tsx
> +  const handleChange = (event: { target: { value: SetStateAction<string> } }): void => {
может лучше ChangeEvent https://stackoverflow.com/questions/40676343/typescript-input-onchange-event-target-value

2021-12-10 14:57 UTC, Beljar commented on src/components/search/search_result/Search_Result.tsx
> +  setIsResultsRendered: any;
any

2021-12-10 14:57 UTC, Beljar commented on src/components/search/search_result/Search_Result.tsx
> +      setIsResultsRendered(true);
странно, title передали в пропсах и отдаем информацию обратно в колбек. Не проще ли в родительском элементе сразу решать, есть ли title?

2021-12-13 09:10 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +        if (res.status !== 200) {
fixed.

2021-12-13 09:10 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +    const res = event.target.value;
fixed.

2021-12-13 09:10 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +  const debouncedValue = useDebounce(searchValue, 500);
fixed.

2021-12-13 11:12 UTC, GlebShulga commented on src/components/search/search_result/Search_Result.tsx
> +  setIsResultsRendered: any;
fixed

2021-12-14 14:41 UTC, Snoopyk8411 requested changes

2021-12-14 14:41 UTC, Snoopyk8411 commented on .vscode/launch.json
> +    "configurations": [
эт что и зачем?)

2021-12-14 14:41 UTC, Snoopyk8411 commented on package.json
> +}
сильно))))

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const requestedCategory = 'Каталог';
текстовая константа наверно должна быть в константах?)

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const SEARCH_API = `${API}/${CATALOG}${requestedCategory}`;
как и search api url)

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      setMenuItems(menuItems);
а может вообще весь хук вынесем в кастомный useFetchCatalogItems?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const menuItems = getMenuItemsFromCategories(catalog.children);
анти паттерн применять функции до их обьявления

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      setMenuItems(menuItems);
заодно видимо и функция переместиться в utils

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/catalog_menu/Catalog_Menu.tsx
> +  const title = 'Каталог';
похоже на дублирование текстовой константы

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/header/Header.tsx
> +  const logoName = 'Shop';
мне кажется эта штука должна быть в константах

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/header/Header.tsx
> +          <div>некоторые другие иконки действий</div>
если это моки - неплохо бы закомментировать согласно правилам, дабы имелась пометка о том, как где и когда и что выпиливать

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/header/header.tsx
> +import { useRef } from 'react';
не понял - зачем нам два одинаковых хедера? выпиливай второй

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/header_bottom_menu/Bottom_Menu.tsx
> +  const headerItem = CATALOG_ITEMS.filter(el => el.groups.includes('Header') && !el.name.includes('Каталог'));
если это массив чего-то, то наверно это не единственное число?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/Search.tsx
> +  const searchIcon = 'Search';
и вновь мне кажется, что эта штука должна быть в константах

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +  const delay = 500;
целый набор констант, которым самое место отдельно в константах

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +  const successfulResponses = 200;
скорее уже STAUS_SUCCESS - это же status code в конце то концов

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +        setIsLoading(false);
а это норм что isLoading в локальном стейте, а не в редаксе?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +  useEffect(() => {
предлагаю также вынести в отдельный хук, например useSearchResult

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +        const res = await axios.get(SEARCH_API);
и вообще-то говоря. Мы общение с серваком осуществляем в сагах. Почему search result в стейте а не в редаксе?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +  const handleChange = (event: { target: { value: SetStateAction<string> } }): void => {
+

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +    dispatch(setIsSearch(true));
непонятно что за isSearch - надо бы детальнее назвать

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +    setSearchValue(res);
не res, а nextSearchValue

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/search_modal/Search_Modal.tsx
> +  const handleClick = (): void => {
ну это видимо handleClose

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/search_modal/Search_Modal.tsx
> +  const title = 'Поиск';
снова мистическая константа

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/search.module.css
> +.search_container {
а че не SCSS? просили же вроде очень

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/search_result/Search_Result.tsx
> +  const cartIcon = 'Cart';
и снова

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +            {isResultsRendered && <button className={inputStyles.button}>{showAllbuttonTitle}</button>}
это не правильно. 
1) если подвязываться на рендер - то это componentDidMount, а в реалиях хуков - хук с зависимостью []
2) подвязываться нужно на searchResult.length - так как, во первых все равно сперва отрисуются элементы и только потом кнопка , во вторых нет результатов - нет и кнопки, в третьих можно управлять при каком количестве элементов вообще отображать эту кнопку

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/components/search/input/input.module.css
> +@media (min-height: 755px) and (max-height: 1060px) {
какие то мистические значения высот - откуда они? и почему высоты вообще?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/constants/index.ts
> +export const LIMIT = '&limit=5';
значение лимита 5 - это тоже константа отдельная, а в будущем может и регулируемый параметр

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/mock-data/svg/cart.svg
> +<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
зачем нужны первые 2 строчки?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/mock-data/svg/catalog.svg
>  <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
зачем доктайпы и иксмл

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/mock-data/svg/catalog.svg
>  <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
?

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/mock-data/svg/search.svg
> +<svg fill="#000000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50" width="20px" height="20px"><path d="M 21 3 C 11.601563 3 4 10.601563 4 20 C 4 29.398438 11.601563 37 21 37 C 24.355469 37 2
вот тут просто свг и всё работает

2021-12-14 14:41 UTC, Snoopyk8411 commented on src/store/shop/selectors.ts
> +export const selectIsSearch = createSelector(selectShop, state => state.isSearch);
непонятно почему isLoading и search results не попали с тор а лежат локально

2021-12-14 14:53 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const requestedCategory = 'Каталог';
fixed

2021-12-14 14:53 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const SEARCH_API = `${API}/${CATALOG}${requestedCategory}`;
fixed

2021-12-14 14:58 UTC, GlebShulga commented on src/components/header/Header.tsx
> +          <div>некоторые другие иконки действий</div>
fixed

2021-12-14 15:01 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +  const successfulResponses = 200;
fixed

2021-12-14 15:07 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +    setSearchValue(res);
fixed

2021-12-14 15:07 UTC, GlebShulga commented on src/components/search/search_modal/Search_Modal.tsx
> +  const handleClick = (): void => {
fixed

2021-12-14 15:08 UTC, GlebShulga commented on src/components/search/search.module.css
> +.search_container {
Это было создано до добавления PostCSS, рейтинг уже делал с scss.

2021-12-14 15:15 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +            {isResultsRendered && <button className={inputStyles.button}>{showAllbuttonTitle}</button>}
fixed

2021-12-14 15:17 UTC, GlebShulga commented on src/constants/index.ts
> +export const LIMIT = '&limit=5';
fixed.

2021-12-14 15:49 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +  const handleChange = (event: { target: { value: SetStateAction<string> } }): void => {
fixed

2021-12-14 15:51 UTC, GlebShulga commented on .vscode/launch.json
> +    "configurations": [
vs code создал этот файл, когда я с debugging экспериментировал. Забыл выпилить.

2021-12-15 06:43 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      setMenuItems(menuItems);
Функцию getMenuItemsFromCategories вынес в tools.
Хук useFetchCatalogItems вынес в hooks.

2021-12-15 06:47 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const menuItems = getMenuItemsFromCategories(catalog.children);
Исправлено после вынесения функции в tools.

2021-12-15 06:55 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +  const title = 'Каталог';
Вынес в константы. Значение одно и то же, но сущности разные. В дальнейшем одна из переменных может быть изменена, поэтому оставляю обе.

2021-12-15 07:08 UTC, GlebShulga commented on src/components/header/Header.tsx
> +  const logoName = 'Shop';
fixed

2021-12-15 07:09 UTC, GlebShulga commented on src/components/header_bottom_menu/Bottom_Menu.tsx
> +  const headerItem = CATALOG_ITEMS.filter(el => el.groups.includes('Header') && !el.name.includes('Каталог'));
fixed

2021-12-15 07:10 UTC, GlebShulga commented on src/components/search/Search.tsx
> +  const searchIcon = 'Search';
fixed

2021-12-15 07:19 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +  const delay = 500;
fixed

2021-12-15 07:21 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +        setIsLoading(false);
isLoading применяется только к поиску. Поскольку решили запрос поиска оставлять в компоненте, то и isLoading тоже логично оставить здесь же.

2021-12-15 07:55 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +        const res = await axios.get(SEARCH_API);
Договорились оставить запрос в компоненте.

2021-12-15 07:57 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +    dispatch(setIsSearch(true));
Переименовал в isSearchUsed.

2021-12-15 08:00 UTC, GlebShulga commented on src/components/search/search_modal/Search_Modal.tsx
> +  const title = 'Поиск';
fixed

2021-12-15 08:06 UTC, GlebShulga commented on src/components/search/search_result/Search_Result.tsx
> +  const cartIcon = 'Cart';
fixed

2021-12-15 08:11 UTC, GlebShulga commented on src/components/search/input/input.module.css
> +@media (min-height: 755px) and (max-height: 1060px) {
Это были остатки неудачного эксперимента. Выпилил.

2021-12-15 08:13 UTC, GlebShulga commented on src/mock-data/svg/cart.svg
> +<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
удалил

2021-12-15 08:14 UTC, GlebShulga commented on src/mock-data/svg/catalog.svg
>  <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
Забыл их удалить, исправился.

2021-12-15 08:17 UTC, GlebShulga commented on src/store/shop/selectors.ts
> +export const selectIsSearch = createSelector(selectShop, state => state.isSearch);
Потому что isLoading и searchResult используются только в одном компоненте и пропсами никуда не передаются.

2021-12-15 08:52 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      setMenuItems(menuItems);
хук вынес в useFetchCatalogItems в hooks
функцию getMenuItemsFromCategories вынес в tools/get-menu-items-from-categories

2021-12-15 08:53 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const SEARCH_API = `${API}/${CATALOG}${requestedCategory}`;
fixed

2021-12-15 08:53 UTC, GlebShulga commented on src/components/catalog_menu/Catalog_Menu.tsx
> +      const requestedCategory = 'Каталог';
fixed

2021-12-15 08:55 UTC, GlebShulga commented on src/components/search/input/Input.tsx
> +  useEffect(() => {
вынес useSearchResult в hooks.

2021-12-15 13:37 UTC, Snoopyk8411 requested changes

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/header/Header.tsx
> +  const logoName = 'Shop';
где fixed то?)

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/header/Header.tsx
> +          <div>некоторые другие иконки действий</div>
не пофикшено)

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/header/Header.tsx
> +  const logoName = 'Shop';
вижу что добавил, но забыл применить)

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/header/header.tsx
> +import { useRef } from 'react';
всё ещё два хедера

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/search/Search.tsx
> +import { setIsModal } from 'store/shop/slice';
я вот все равно не вкуриваю, что такое isModal? isModalOpened? надо бы точнее переименовать

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/search/input/Input.tsx
> +    dispatch(setIsSearch(true));
что то не видно изменений

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/components/search/search_modal/Search_Modal.tsx
> +    dispatch(setIsModal(false));
все таки это должно быть isModalOpened видимо)

2021-12-15 13:37 UTC, Snoopyk8411 commented on src/mock-data/svg/cart.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
ты иконку сменил чтоли?

2021-12-15 14:04 UTC, GlebShulga commented on src/mock-data/svg/cart.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
всего лишь убрал лишнее

2021-12-15 14:04 UTC, GlebShulga commented on src/components/search/search_modal/Search_Modal.tsx
> +    dispatch(setIsModal(false));
fixed

2021-12-15 14:13 UTC, GlebShulga commented on src/components/search/Search.tsx
> +import { setIsModal } from 'store/shop/slice';
fixed

2021-12-16 10:24 UTC, Snoopyk8411 approved these changes

2021-12-16 10:53 UTC, merged