Feature/nbpp 21 geo component
Snoopyk8411/nbbp-fe pull request #19
Opened 2021-12-14 08:48 UTC by py-cs

2021-12-14 10:43 UTC, GlebShulga approved these changes

2021-12-14 10:43 UTC, GlebShulga commented on styles/globals.css
> +  --clr-neutral-700: #333333;
договорились писать цвета в rgb

2021-12-14 10:43 UTC, GlebShulga commented on src/components/geo-balloon/geo-balloon.tsx
> +        Выбрать
Весь текст выносим в переменные

2021-12-14 13:57 UTC, Snoopyk8411 requested changes

2021-12-14 13:57 UTC, Snoopyk8411 commented on public/assets/geo.svg
> +          {' '}
эта строчка зачем нужна?)

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo-balloon/geo-balloon.tsx
> +export const GeoBalloon: FC<IGeoBaloonProps> = ({ point, handleSelect }) => {
а точно тайпскрипту не нужно здесь указывать например, что вернет функция?

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo-balloon/geo-balloon.tsx
> +        Выбрать
+

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo/geo.tsx
> +export const Geo = (): JSX.Element => {
GeoWidget тогда уж наверно

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo/geo.tsx
> +      <button className={geoStyles.geo__toggle} onClick={(): void => setIsDropdownOpen(!isDropDownOpen)} type='button'>
(): void => setIsDropdownOpen(!isDropDownOpen) в данном случае функцию бы вынести в отдельный handle

2021-12-14 13:57 UTC, Snoopyk8411 commented on styles/globals.css
> +  --clr-neutral-700: #333333;
+

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo/geo.tsx
> +                    key={index}
а это точно корректный key? договорились использовать что-то более уникальное

2021-12-14 13:57 UTC, Snoopyk8411 commented on src/components/geo/geo.tsx
> +                      ReactDOM.hydrate(
прикольно, я бы сделал просто balloonContent: `<div id="balloon"></div>`,
а потом ReactDOM.render
но если работает - ладушки)

2021-12-15 07:52 UTC, py-cs commented on styles/globals.css
> +  --clr-neutral-700: #333333;
Исправлено

2021-12-15 07:52 UTC, py-cs commented on src/components/geo-balloon/geo-balloon.tsx
> +        Выбрать
Исправлено

2021-12-15 07:57 UTC, py-cs commented on public/assets/geo.svg
> +          {' '}
Удалено

2021-12-15 07:58 UTC, py-cs commented on src/components/geo-balloon/geo-balloon.tsx
> +export const GeoBalloon: FC<IGeoBaloonProps> = ({ point, handleSelect }) => {
точно, FC = (props: T) => JSX.Element

2021-12-15 07:58 UTC, py-cs commented on src/components/geo/geo.tsx
> +export const Geo = (): JSX.Element => {
Исправлено

2021-12-15 08:03 UTC, py-cs commented on src/components/geo/geo.tsx
> +      <button className={geoStyles.geo__toggle} onClick={(): void => setIsDropdownOpen(!isDropDownOpen)} type='button'>
Исправлено

2021-12-15 08:04 UTC, py-cs commented on src/components/geo/geo.tsx
> +                    key={index}
Исправлено

2021-12-15 08:16 UTC, py-cs commented on src/components/geo/geo.tsx
> +                      ReactDOM.hydrate(
Насколько я понял, суть подхода в том, чтобы все точки сначала наполнить статическим html, а гидрировать логикой только конкретную точку при её открытии. С маленьким количеством точек и единственной кнопкой в балуне наверное не принципиально, но пусть будет с оптимизацией на перспективу.

2021-12-15 13:41 UTC, Snoopyk8411 approved these changes

2021-12-15 13:41 UTC, Snoopyk8411 commented on src/components/geo-balloon/geo-balloon.tsx
> +export const GeoBalloon: FC<IGeoBaloonProps> = ({ point, handleSelect }) => {
=> JSX.Element - вот эта часть отсутствует)

2021-12-15 13:43 UTC, merged