implement test page in contributor's folder
Snoopyk8411/nbbp-fe pull request #2
Opened 2021-11-03 15:32 UTC by Beljar

Test PR

2021-11-12 15:23 UTC, Snoopyk8411 requested changes

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/Cookbook.tsx
> +import styles from './index.module.css';
лучше cookbookStyles

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/Cookbook.tsx
> +    <h1>COOKBOOK</h1>
тексты лучше в константы

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +type Props = {
productsProps

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +export const ProductsSelector: React.FC<Props> = ({ products = [], loadProducts = () => [], onChange }) => {
ProductsSelect

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +    loadProducts();
давай для образовательных целей сделаем это методами next.js

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +          onChange={e => {
функции обработчики стоит выносить в отдельные переменные const handleChange

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +import * as React from 'react';
это не нужно

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +  React.useEffect(() => {
это так не делается

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/ProductsSelector.tsx
> +  React.useEffect(() => {
делается вот так import { useEffect } from 'react';

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/RecipeCard.tsx
> +import * as React from 'react';
снова)

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/RecipeCard.tsx
> +    {recipe.ingridients.length
грамматическая ошибка

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelector/productsSelector.module.css
> +  min-width: 150px;
надо бы помощнее верстку

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +import * as React from 'react';
снова

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +  const [curIngridients, setCurIngridients] = React.useState<IRecipeIngridient[]>([]);
грамматическая ошибка

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +  const [curIngridients, setCurIngridients] = React.useState<IRecipeIngridient[]>([]);
может стоить сделать константу
const DEFAULT_VALUES = {
ingredients: [],
name: '',
amount: 0,
product: undefined // null
};

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +  const [curProduct, setCurProduct] = React.useState<IProduct>();
а ты что нет default value?

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +        <h2>Specify amount</h2>
разбить на компоненты и убрать хардкод функций

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +          disabled={!(curIngridients.length && curName)}
просьба выносить логические выражения в константы/флаги и применять

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +        <RecipeCard recipe={{ id: 0, ingridients: curIngridients }} />
убрать хардкод магических обьектов/текстов/цифер

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/recipeCreate.module.css
> +  margin-left: 150px;
а ещё есть https://habr.com/ru/post/468327/ flex-gap

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/recipeCreate.module.css
> +.wrapper > *:not(:first-child) {
хорошим тоном считается присвоение css, ни в коем случае не html элементам, но классам на них или по id

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/recipeCreate.module.css
> +  margin-left: 150px;
а че не rem?

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/recipeCreate.module.css
> +  margin: 10px 0;
а можно сделать класс amount_component например

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeList/RecipeList.tsx
> +    {recipes?.length ? recipes?.map((recipe, idx) => <RecipeCard key={idx} recipe={recipe} />) : 'no recipes found'}
лучше выносить логику в переменные, например
const hasRecipes = recipes && recipes.length !== 0;
далее
{hasRecipes ? recipes.map((recipe, idx) => <RecipeCard key={idx} recipe={recipe} />) : 'no recipes found'}

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeList/RecipeList.tsx
> +    {recipes?.length ? recipes?.map((recipe, idx) => <RecipeCard key={idx} recipe={recipe} />) : 'no recipes found'}
а ещё лучше, не просто 'no recipes found'
а хотя бы //span>'no recipes found'//span> дабы стилизовать было удобнее в дальнейшем
на реальных проектах почти не бывает текстов которые отрисовываются as is, а на враппер сложно добавить стили, которые применимы для текста и не аффектнут на массив компонент при случае

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeList/recipeList.module.css
> +  margin: 30px;
rem

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/store/cookbook-products-data-mock.json
> +[
моки это отлично, но давай, за ради образовательных целей - эти моки будет отдавать бэк next js, дабы мы понимали как он работает

2021-11-12 15:23 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/saga-load-init-data.ts
> +function* recipesLoadInitDataFlow() {
всегда оборачивай генераторы особенно в сагах в try/catch блок - ВСЕГДА

2021-11-18 19:13 UTC, Snoopyk8411 requested changes

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/IngredientCreate/IngredientCreate.tsx
> +  const isReady = () => isProduct(product) && isAmountValid(amount);
если это isReady - то это не может быть функция, это флаг.
функция - это всегда действие

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/IngredientCreate/index.ts
> +export * from './IngredientCreate';
а зачем?) у тебя экспортится только один компонент - wildcard мы стараемся не использовать, а здесь он ещё и не нужен совершенно

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +  const selectHandler = useCallback(
тогда уж handleSelect

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +      const { target: { selectedIndex = undefined } = {} } = e || {};
использовать значение по умолчанию = undefined избыточно) оно итак будет undefined, если отсутствует

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +      const selectedProduct = selectedIndex ? products[selectedIndex] : undefined;
или это можно записать как const selectedProduct = selectedIndex && products[selectedIndex];
в текущей реализации будет тоже самое)

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/RecipeCard.tsx
> +    {recipe.ingredients.length
следует деструктурировать свойства в начале и затем использовать
const { name, ingredients } = recipe;

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/RecipeCard.tsx
> +      ? recipe.ingredients.map((recipe, idx) => <div key={idx}>{`${recipe.product.name} - ${recipe.amount}`}</div>)
не используем сокращений - index не длинное имя
+ индекс использовать в качестве ключа антипаттерн - нужно использовать более уникальные ключи

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/constants.ts
> +export const NO_INRGEDIENTS = 'no ingredients';
грамматическая ошибка

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCard/index.ts
> +export * from './RecipeCard';
снова непонятная конструкция

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +  const isReady = () => ingredients.length && name;
снова, это флаг а не функция

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +    onClear();
зачем здесь onClear?)

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +  const createRecipeHandler = () => {
handleCreateRecipe - таков правильный нейминг

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/RecipeCreate.tsx
> +      <button onClick={onClear} disabled={!ingredients.length}>
стоит выносить в отдельную константу const isClearDisabled = !ingredients.length; и использовать

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeCreate/index.ts
> +export * from './RecipeCreate';
снова

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeList/RecipeList.tsx
> +    {recipes?.length ? recipes?.map((recipe, idx) => <RecipeCard key={idx} recipe={recipe} />) : 'no recipes found'}
не исправлено

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeWizard/RecipeWizard.tsx
> +    setIngredients([]);
тык ты же наверху сделал handleClear - вот его и вызывай, зачем дублировать то

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeWizard/RecipeWizard.tsx
> +  const recipeCreateHandler = useCallback((recipe: IRecipe) => {
handleCreateRecipe

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeWizard/RecipeWizard.tsx
> +  const clearHandler = useCallback(() => {
handleClear или в данном случае просто clear

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeWizard/RecipeWizard.tsx
> +        <IngredientCreate product={product} onCreate={ingredient => setIngredients([...ingredients, ingredient])} />
ingredient => setIngredients([...ingredients, ingredient]) - выносим в отдельный handle

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/layout/cookbook/utils/isProduct.ts
> +  Object.prototype.hasOwnProperty.call(product, 'id') &&
уххх, вообще говоря есть методы и попроще
например: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for...in
или https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames

да и к слову эту проверку положит null
---
так что я бы предложил

=> !!product && product['id'] && product['name'], ну или взять лучшее от двух вариантов.
Но если тебе прям нужно понимать присутствует ли свойство в обьекте (именно присутствует, а не просто undefined), то я бы пересмотрел такой подход - очень не надежно всё это выглядит и поддерживать тяжело, лучше пересмотреть проверку

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/pages/contributors/Ilia_Kotov/index.tsx
> +  const products: IProductsData = await axios.get(COOKBOOK_API.products).then(res => res.data);
не обработаны ошибки

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookProducts/saga-load-init-data.ts
> +    yield put(productsActions.setIsLoading(true));
а лоадера я что-то не видел среди компонент

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookProducts/saga-load-init-data.ts
> +    yield put(productsActions.setError(error as Error));
отображения ошибки, кстати, тоже

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/saga-load-init-data.ts
> +    const recipes: IRecipeData = yield call(() => axios.get<IRecipeData>(COOKBOOK_API.recipes).then(res => res.data));
а тут и лоадинга нет совсем

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/saga-load-init-data.ts
> +    yield put(recipesAction.setIsLoading(false));
но при этом тут он в false падает)))

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/selectors.ts
> +export const getRecipes = createSelector(getRecipesStore, (recipesStore: IRecipesStore) => recipesStore.data);
договорились же, что селектора это selectRecipes - get это вызов get метода

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookProducts/selectors.ts
> +export const getProducts = createSelector(getProductsStore, (products: IProductsStore): IProductsData => products.data);
select, а не get

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/slice.ts
> +      state.data.push({ ...action.payload, id: (state.counter += 1) });
не не не, давай первым шагом мы state.counter += 1;
а вот следующим уже id: state.counter;
а не в одно действие

2021-11-18 19:13 UTC, Snoopyk8411 commented on src/store/sagas.ts
> +import recipesLoadInitDataWatcher from './cookbookRecipes/saga-load-init-data';
хм, я немного запутался, я думал init data ты прокидываешь через next - почему здесь тогда init?

2021-11-19 22:45 UTC, Beljar commented on src/store/sagas.ts
> +import recipesLoadInitDataWatcher from './cookbookRecipes/saga-load-init-data';
В итоге я products прокидываю через staticProps, а recipes через саги. Чтобы и такой и такой пример по итогу получился.

2021-11-22 17:31 UTC, Snoopyk8411 requested changes

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/IngredientCreate/IngredientCreate.tsx
> +  const changeAmountHandler = (e: ChangeEvent<HTMLInputElement>) => {
во всем пулл реквесте, одна и та же ошибка - функция это ДЕЙСТВИЕ. handler - существительное, handle - глагол.

не changeAmountHandler, а handleChangeAmount!!!!!!!!!!!!!!!!!!

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/IngredientCreate/index.ts
> +export * from './IngredientCreate';
нет ответа

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +      const selectedProduct = products[index] || undefined;
|| undefined - избыточно, у products[index] два варианта итак, либо данные есть, либо они undefined

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/constants.ts
> +const API_HOSTS = {
кажется эти константы уж слишком глобально заданы

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +              onClick={(): void => selectHandler(idx)}
никаких анонимных коллбэков в качестве свойств. Уже писал же - делаем handleSomething = (): void => selectHandler(idx);

и затем onClick={handleSomething}

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ProductsSelect/ProductsSelect.tsx
> +  error: state.products.error,
очевидно же, что и тут надо доставать значение селектором

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeList/RecipeList.tsx
> +        recipes.map((recipe, idx) => <RecipeCard key={idx} recipe={recipe} />)
key={idx} - это антипаттерн, ключи должны быть не индексами, или хотя бы не только индексами

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/RecipeWizard/RecipeWizard.tsx
> +  const handleAddIngredient = (ingredient: IRecipeIngredient) => setIngredients([...ingredients, ingredient]);
а здесь вроде исправлено - почему выше тогда не исправлено?

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ui/ErrorFrame/ErrorFrame.tsx
> +  useEffect(() => {
прикольно конечно, но в реакте так не делается) не знаю точной задумки, но кажется ты хотел
https://ru.reactjs.org/docs/portals.html это
и в любом случае, это какая то императивщина. Эта штука должна быть сделана средствами реакт и JSX

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ui/ErrorFrame/ErrorFrame.tsx
> +  const [curMessages, setCurMessages] = useState<string[]>([]);
никаких сокращений в именованиях - вебпак сам потом всё сократит. А заставлять гадать current это или curry - антипаттерн

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ui/ErrorFrame/ErrorFrame.tsx
> +    setTimeout(() => setCurMessages(curMessages?.slice(1)), ERROR_TIMEOUT);
а это что зачем и для чего?

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/layout/cookbook/ui/ErrorFrame/ErrorFrame.tsx
> +  return container?.current ? createPortal(errors, container?.current) : null;
а между прочим - зачем вообще здесь порталы? порталы нужны для модалок

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/saga-load-recipes.ts
> +    const recipes: IRecipeData = yield call(() => axios.get<IRecipeData>(COOKBOOK_API.recipes).then(res => res.data));
нет нет нет - спроси у коллегб да и в коде можешь посмотреть - axios запросы мы выносим в отдельные файлы и в саги импортируем потом

2021-11-22 17:31 UTC, Snoopyk8411 commented on src/store/cookbookRecipes/selectors.ts
> +export const selectRecipes = createSelector(selectRecipesStore, (recipesStore: IRecipesStore) => recipesStore.data);
странно что нет селекторов для error и isLoading

2021-11-24 11:23 UTC, Snoopyk8411 requested changes

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/layout/contributors/Ilia_Kotov/cookbook/ProductsSelect/ProductsSelect.tsx
> +            const handleClick = (): void => handleSelect(index);
я очень извиняюсь, наверно это я в прошлом ревью некорректно прокомментил. Конкретно тут конечно же стоит оставить onClick={(): void => handleSelect(index)}

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/layout/contributors/Ilia_Kotov/cookbook/components/ErrorMessage/ErrorMessage.tsx
> +  const [container] = useState(document.querySelector(`#${ERROR_FRAME_ID}`) as HTMLDivElement);
ну во первых, ты уверен что useState? мне кажется что для этих целей нужен useRef

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/layout/contributors/Ilia_Kotov/cookbook/components/ErrorFrame/ErrorFrame.tsx
> +  return createPortal(errorFrame, bodyEl);
зачем тебе это нужно? Сделай просто в body <div id={ERROR_FRAME_ID}></div>

а враппер с позиционированием и ошибки уже будут в ErrorMessage например
Либо , ты и css можешь в лэйауте прописать - ЗАЧЕМ здесь порталы использовать? да ещё и динамически

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/pages/contributors/Ilia_Kotov/index.tsx
> +    <ErrorFrame />
если ты тут таким образом добавляешь ErrorFrame, зачем ты в нем самом используешь портал? он итак отрендериться в body

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/selectors.ts
> +export const selectRecipes = createSelector(selectRecipesStore, (recipesStore: IRecipesStore) => recipesStore.data);
называй аргументы также как они называются в сторе, не recipesStore, а recipes - иначе это вводит в заблуждение людей и невозможно селекторы читать

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/saga-load-recipes.ts
> +    const recipes: IRecipeData = yield call(() => apiGetRecipes());
зачем здесь анонимная функция? просьба перед использованием - читать документацию как работают методы (в данном случае эффекты саги)

2021-11-24 11:23 UTC, Snoopyk8411 commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/api-get-recipes.ts
> +    .catch(error => error);
да уж хотя бы console.log(error)

2021-11-24 11:23 UTC, Snoopyk8411 commented on tsconfig.json
> +      "src/*": ["../src/*"],
а это зачем?
"baseUrl": "src" же есть

2021-11-24 11:41 UTC, Beljar commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/api-get-recipes.ts
> +    .catch(error => error);
error передается в стор, текст ошики затем выводится вспывающим сообщением на странице

2021-11-24 14:06 UTC, asnoskov requested changes

2021-11-24 14:06 UTC, asnoskov commented on src/layout/cookbook/IngredientCreate/IngredientCreate.tsx
> +  const createIngredientHandler = () => {
Не критично, но возможно стоит использовать нэйминг вида handleEvent вместе eventHandler. Не знаю является ли это общим гайдлайном, но в доке по реакту и встречающихся мне примерах используется первый вариант (onEvent для событий, handleEvent - для обработчиков).

2021-11-24 14:06 UTC, asnoskov commented on src/layout/cookbook/ProductsSelect/productsSelect.module.css
> +  box-shadow: inset 0 0 6px var(--secondary-ui-color);
Думаю, стоит использовать rem/em и здесь, чтобы тень оставалась пропорциональной паддингам и т.д. при масштабировании шрифта.

2021-11-24 14:06 UTC, asnoskov commented on src/tools/is-objects-equal.ts
> +export const isObjectsEqual = (
Для нэйминга функций лучше действие, например checkObjectsEqual

2021-11-25 12:21 UTC, Beljar commented on src/tools/is-objects-equal.ts
> +export const isObjectsEqual = (
Это не мой код) Просто, видимо, линтер форматнул что-то и оно в changes попало.

2021-11-25 12:35 UTC, Beljar commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/selectors.ts
> +export const selectRecipes = createSelector(selectRecipesStore, (recipesStore: IRecipesStore) => recipesStore.data);
тут не понял. У меня есть селектор, который выбирает стор, а есть который выбирает recipes из этого стора. Если вместо recipesStore назвать recipes, то как потом назвать сами recipes?

2021-11-25 12:41 UTC, Beljar commented on src/pages/contributors/Ilia_Kotov/index.tsx
> +    <ErrorFrame />
нет, он оборачивается в div с id="__next". Я же про это спрашивал: можно ли, чтобы контейнер с ошибками лежал внутри рутового дива, а не в body, ты сказал, надо именно в body.

2021-11-25 15:25 UTC, Snoopyk8411 requested changes

2021-11-25 15:25 UTC, Snoopyk8411 commented on src/pages/_document.tsx
> +          {hasErrorFrame && <div id={ERROR_FRAME_ID}></div>}
Сделай его общим, вне зависимости от рута

2021-11-25 15:25 UTC, Snoopyk8411 commented on src/pages/_document.tsx
> +    console.log(ctx.pathname);
консоль лог лишний

2021-11-25 15:25 UTC, Snoopyk8411 commented on src/pages/_document.tsx
> +  path = '';
какой то непонятный кусок кода - видимо его тоже надо выпилить

2021-11-25 15:25 UTC, Snoopyk8411 commented on src/store/contributors/Ilia_Kotov/cookbookRecipes/selectors.ts
> +export const selectRecipes = createSelector(selectRecipesStore, (recipesStore: IRecipesStore) => recipesStore.data);
ну я бы предложил
const selectRecipesData = (store: RootState): IRecipesStore => store.recipes;
export const selectRecipes = createSelector(selectRecipesData, (recipesData: IRecipesStoreData) => recipesStore.data);

или типо того - итак понятно, что из стора тянется - получается масло масляное

2021-11-26 10:57 UTC, asnoskov approved these changes

2021-11-26 12:26 UTC, Snoopyk8411 approved these changes

2021-11-26 12:29 UTC, merged