Feature/nbpp 24 thumbnail/image component
Snoopyk8411/nbbp-fe pull request #20
Opened 2021-12-14 23:22 UTC by Beljar

2021-12-15 11:28 UTC, asnoskov commented on src/components/Image/Image.tsx
> +  const imgWrapperRef = useRef() as React.MutableRefObject<HTMLDivElement>;
у useRef есть generic-версия. Думаю, лучше использовать её: useRef<React.MutableRefObject<HTMLDivElement>>, тогда не придется type assertion делать

2021-12-15 11:28 UTC, asnoskov commented on src/components/Image/Image.tsx
> +  const imgRef = useRef() as React.MutableRefObject<HTMLImageElement>;
useRef<React.MutableRefObject<HTMLImageElement>> (см. предыдущий коммент)

2021-12-15 11:28 UTC, asnoskov commented on src/components/Image/Image.tsx
> +        return;
а для чего нужен пустой обработчик?

2021-12-15 11:28 UTC, asnoskov commented on src/components/Image/Image.tsx
> +        <source
Исключают ли флаги useWebp и useAvif друг друга? Если да, то я бы вынес image type (?) в отдельную переменную, чтобы не дублировать верстку.
changeImageExtension(), думаю, тоже лучше расчитать заранее, чтобы не дергать два раза.
Что-то вроде такого:
const imageType = useWebp ? IMAGE_TYPES.WEBP: IMAGE_TYPES.AVIF;
const srcSet/*или более подходящее название*/ = changeImageExtension(imgSrc, imageType);
..
isVisible && (useAvif || useWebp) && (
        <source
          data-srcset={srcSet}
          srcSet={srcSet}
          type={String(imageType)}
        />
      )}

2021-12-15 13:52 UTC, Snoopyk8411 requested changes

2021-12-15 13:52 UTC, Snoopyk8411 commented on src/components/Image/Image.tsx
> +const ITEM_TYPE = 'http://schema.org/ImageObject';
это бы в константы в отдельный файл закинуть

2021-12-15 13:52 UTC, Snoopyk8411 commented on src/components/Image/Image.tsx
> +  const imgWrapperRef = useRef() as React.MutableRefObject<HTMLDivElement>;
согласен

2021-12-15 13:52 UTC, Snoopyk8411 commented on src/components/Image/Image.tsx
> +  const imgRef = useRef() as React.MutableRefObject<HTMLImageElement>;
согласен

2021-12-15 13:52 UTC, Snoopyk8411 commented on src/hooks/use-intersection-observer.ts
> +        rootMargin: '50% 50%',
а может '50% 50%' превратить в константу? чтобы понять было что это за магические проценты)

2021-12-15 14:16 UTC, Beljar commented on src/components/Image/Image.tsx
> +        return;
чтобы убрать уже установленный. Если fallback картинка недоступна, то опять вызовется onError и это все зациклится, если его не очистить. Может, есть какой-то более красивый способ это делать?

2021-12-16 12:50 UTC, Snoopyk8411 approved these changes

2021-12-16 13:06 UTC, merged