NBPP-6 simple todo list
Snoopyk8411/nbbp-fe pull request #3
Opened 2021-11-09 08:23 UTC by asnoskov

Implemented todo list page

2021-11-12 13:23 UTC, Snoopyk8411 requested changes

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.module.css
> +.addTodo {
css классы мы именуем по snakecase - add_todo, и имена классов должны семантически показывать к какому куски верстки они относятся

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +import styles from './add-todo.module.css';
import addTodoStyles from './add-todo.module.css';
...
className={addTodoStyles.title}
...
className={addTodoStyles.content}

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.module.css
> +    padding: 16px;
раз решили в rem - давайте писать в rem

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +  const [name, setName] = useState('');
предпочтительней использовать EMPTY_VALUE = '' константу

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +        <input type='text' id='name' value={name} onChange={e => setName(e.target.value)} />
давайте все таки всегда делать handler для onSomething событий
onChange={handleChange}
где
const handleChange = ({ target: value }) => setName(e.target.value);

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +  const addTodo = () => {
если нет return, то {} не нужны
const addTodo = () => dispatch(
      todosActions.addTodo({
        id: 0,
        name: name,
        description: description,
        isDone: false,
      }),
    );

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +      todosActions.addTodo({
1) стоит сделать утилиту
// helpers.ts and used by slice.ts
const parseDataToTODOItem = (data) => {
const { name, description } = data;
return {
  id: 0,
  name,
  description,
  isDone: false,
}
2) эту функцию стоит использовать в редьюсере, перед добавлением в стор данных - так как, это является обогащением данных технической инфой, что по уровню абстракций соответствуют как раз редьюсеру - компоненту эта инфа ни к чему

Поэтому логичнее сделать как-то так

const addTodo = () => {
 const todoItemData = { name, description };
 dispatch(todoActions.addTodo(todoItemData));
};

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +  const isAddDisabled = () => {
если это is - то это флаг, а функция это всегда действие, тобишь
1) это сделать isAddDisabled флагом и передавать результат функции validate,
2) переименовать в checkAddDisablement

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +      id: 0,
тот же посыл - эти данные не нужны компоненту да и валидации тоже. 
вполне можешь упростить до
const checkAddDisablement = () => !validate({ name, description });

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +        <input type='text' id='name' value={name} onChange={e => setName(e.target.value)} />
ну я бы
1) вынес все id в константы
2) сделал бы их уникальными
id="name" скорее всего есть в 10+ местах в приложении, и возможно что два компонента с одним id встретятся на одной странице
id={TODO_NAME_INPUT} где const TODO_NAME_INPUT = 'add_todo_name'
3) и туда же в константы имена лэйблов Name:

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +        <textarea id='description' cols={30} rows={10} value={description} onChange={e => setDesctiption(e.target.value)}></textarea>
cols/rows рекомендую тоже в константы, как и любые магические числа

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +          <input type='button' onClick={() => addTodo()} disabled={isAddDisabled()} value='Add todo' />
Лучше использовать семантическую разметку, а именно для кнопок тэг "button"

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +          <input type='button' onClick={() => addTodo()} disabled={isAddDisabled()} value='Add todo' />
ну и type submit

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.module.css
> +    border-radius: 8px;
why пиксели?)

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.module.css
> +.todo {
повторюсь, классы стоит именовать семантичнее

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.tsx
> +import * as models from 'tools/types/aleksei/models';
1) не рекомендуется, использовать конструкцию import * as models в файле, где models применяется
обычно рядом с models.ts создают файл index.ts c содержимым
// index.ts
import * as models from './models';
export models;

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.tsx
> +const Todo: React.FC<models.Todo> = (todo: models.Todo) => {
по поводу конвенции, и это стоит !! добавить в style guide !!
типы мы называем с заглавной I и составляем по правилу I{{SomeIdentificator}}Props в нашем случае ITodoProps

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.tsx
> +      <p>{todo.description}</p>
Обьект с данными для компонента, ровно как и props, стоит и нужно деструктурировать в самом начале компонента
+ в реакт компонентах переданные параметры всегда называются props
// ---
const Todo: React.FC<models.Todo> = (props: models.Todo) => {
const {
description,
name,
isDone } = props;
...

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/components/aleksei/todo/todo.tsx
> +        <button onClick={() => dispatch(todosActions.removeTodo(todo))}>Delete</button>
не анонимные функции, но handleDoneClick, handleDeleteClick

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +const Todos: NextPage = () => {
TodoList

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +const Todos: NextPage = () => {
TodoListPage*

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.module.css
> +.todos {
есть куча альтернатив - wrapper, content, mainpart, box,

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +import Todo from 'components/aleksei/todo/todo';
нарушен порядок импортов

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +        <h3>Remaining:</h3>
это и должны быть компоненты TodoList

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +        <h3>Remaining:</h3>
title
list
emptyListTitle

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +const Todos: NextPage = () => {
TodosPage

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/pages/contributors/aleksei/todos.tsx
> +  const remainingTodos = useMemo(() => todos.filter(todo => !todo.isDone), [todos]);
это не является common practice - более верно, разделять эти два списка через селекторы

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/tools/types/aleksei/models.tsx
> +export interface Todo {
нэйминг

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/store/aleksei/todos/slice.ts
> +  todos: [
давай лучше в образовательных целях, моковые значения буду передаваться с сервера по канонам next.js

2021-11-12 13:23 UTC, Snoopyk8411 commented on src/store/aleksei/todos/slice.ts
> +      const nextId = state.todos.reduce((maxId, todo) => (maxId > todo.id ? maxId : todo.id), 0) + 1;
1) const nextId = state.todos.reduce((maxId, todo) => (Math.max(maxId, todo.id)), 0) + 1;
2) может есть смысл этот редьюс в селекторы засунуть?

2021-11-18 11:15 UTC, GlebShulga commented on src/components/aleksei/add-todo/add-todo.tsx
> +  const checkAddDisabled = () => {
обычно в реакте такие проверки делаются через переменную лежащую в useState.
```
  const [isAddButtonDisabled, setIsAddButtonDisabled] = useState(true)
  useEffect(() => {
    setIsAddButtonDisabled(!validateName(name))
  }, [name]);
...
          <button onClick={() => addTodo()} disabled={isAddButtonDisabled}>
            Add todo
          </button>
```

2021-11-18 11:15 UTC, GlebShulga commented on src/pages/contributors/aleksei/todos.tsx
> +        <ToDoList title={'Remaining'} list={remainingTodos} emptyListTitle={'Nothing is remaining'} />
Выбери что-то одно. Либо вынеси в константу, либо убери {...}.

2021-11-18 11:15 UTC, GlebShulga commented on src/components/aleksei/add-todo/add-todo.tsx
> +  const addTodo = () =>
Предлгаю перенести сразу в handleAddTodoClick

```
  const handleAddTodoClick = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    dispatch(
      todosActions.addTodo({
        name,
        description,
      }),
    );
  };
```

2021-11-18 11:15 UTC, GlebShulga commented on src/components/aleksei/todo/todo.tsx
> +  const handleDoneClick = () => todo.id && dispatch(todosActions.markDone({ id: todo.id }));
Если добавить вторую задачу с список и отметить её как Done, то её статус изменится только при следующем ре-ренедере.
![Screenshot 2021-11-18 140652](https://user-images.githubusercontent.com/67621167/142404505-4973156b-6059-4a99-8b54-04d3b5768e97.png)

2021-11-18 18:42 UTC, Snoopyk8411 commented on src/components/aleksei/add-todo/add-todo.tsx
> +import * as addTodoConst from './const';
все же не const, мы файлы именуем как constants без сокращений

2021-11-18 18:42 UTC, Snoopyk8411 approved these changes

2021-11-22 08:16 UTC, GlebShulga approved these changes

2021-11-22 15:06 UTC, Snoopyk8411 approved these changes

2021-11-22 15:06 UTC, Snoopyk8411 commented on src/tools/types/aleksei/models.ts
> +export class Todo implements ITodo {
а это зачем?

2021-11-23 13:06 UTC, merged