Feature nbpp 7 contributors page
Snoopyk8411/nbbp-fe pull request #4
Opened 2021-11-10 07:46 UTC by GlebShulga

2021-11-10 15:17 UTC, py-cs commented on src/layout/gleb/components/layout/Layout.tsx
> +          {isNotesroute ? 'Go to the Picture' : 'Go to Notes'}
От роутера и onClickNavigation можно избавиться:

<Link href={isNotesRoute ? routes.main : routes.notes>}>
  <a className={styles.header_title}>
    {isNotesroute ? 'Go to the Picture' : 'Go to Notes'}
  </a>
</Link>

2021-11-11 12:05 UTC, Snoopyk8411 requested changes

2021-11-11 12:05 UTC, Snoopyk8411 commented on jest.config.mjs
> +  moduleDirectories: ["node_modules", "src"]
Здесь стоит добавить комментарий 
// node_modules is default option

2021-11-11 12:05 UTC, Snoopyk8411 commented on next.config.mjs
> +    domains: ["localhost", "api.nasa.gov"],
лучше этот момент, вынести в отдельный константы в файл constants.ts
например так:
// constants.ts
// hosts
const API_HOSTS = {
imageComponent: {
 localAPIHost: 'localhost',
 nasaAPIHost: 'api.nasa.gov',
},
};
export const IMAGE_LOAD_DOMAINS = Object.keys(API_HOSTS.imageComponent).map((itemId) => API_HOSTS.imageComponent[itemId]);

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/hooks/use-app-selector.ts
> +
стоит добавить комментарий
// Use it by default, as it correctly typed utility

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/hooks/use-app-selector.ts
> +
и добавить этот пункт в code style

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +type Props = {
стоит переименовать в CreateNoteProps

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    setTitle(e.target.value);
1) const { target: { value = '' } = {}} = e || {};
setTitle(value);

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const [title, setTitle] = useState('');
лично я рекомендую, заводить константу отдельно
const EMPTY_VALUE = '';
и использовать по месту.
useState(EMPTY_VALUE);

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const [error, setError] = useState(false);
раз это boolean, то он должен именоваться с приставки is - поскольку это флаг получается
следовательно 
const [isError, setIsError] = useState(false);

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const onChangeNote = (e: ChangeEvent<HTMLTextAreaElement>) => {
если onChangeNote прокидывается извне то да, если он определяется внутри то это handleChangeNote
// если этого нет с стайлгайде просьба добавить

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const onClickaddNote = () => {
handle

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    if (title.length <= 20 && title.length >= 3) {
давай мы попробуем сделать чуть иначе
const handleClickAddNote = () => {
const titleLength = title.length;
const isTitleLengthValid = titleLength <= 20 && titleLength >= 3;
if (isTitleLengthValid) {
  addNote(title);
}

setIsError(!isTitleLengthValid);
}

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    if (e.key === 'Enter') {
Enter как и Backspace стоит вынести в enum глобальную константу

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          rows={3}
Магические числа стоит выносить в константы

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          placeholder='Write new note'
плэйсхолдеры тоже

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          <button type='button' onClick={onClickaddNote} className={styles.addNoteButton__disabled} disabled>
// перед return
const addNoteButtonClassName = `addNoteButton${isError ? '__disabled' : ''}`;

<button
  type='button'
  onClick={handleClickAddNote}
  className={styles[addNoteButtonClassName]}
  disabled={isError}
>
{ADD_NOTE_BTN_TEXT}
</button>

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +      {error && (
я бы порекомендовал в отдельный компонент вынести

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +  margin: 20px 0;
или пиксели или rem

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +  background-color: rgb(229, 231, 235);
цвета стоит выносить в переменные

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +  color: #1f2937;
так hex или rgb?

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +.addNoteButton {
в css используем snake case -> add_note_button

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +  background-color: rgb(108, 188, 214);
а почему не background?

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +    isNotesroute ? router.push(`/contributors/gleb`) : router.push(`/contributors/gleb/notes`);
стоит вынести роуты в константы
причем
// constants.ts
const MAIN_ROUTE = `/contributors/gleb`;
const NOTES_PART = '/notes';
const NOTES_ROUTE = MAIN_ROUTE + NOTES_PART;

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +        <button className={styles.header_title} data-testid='HeaderTitle' onClick={onClickNavigation}>
handleClick

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +          {isNotesroute ? 'Go to the Picture' : 'Go to Notes'}
{isNotesRoute ? GO_TO_MAIN : GO_TO_NOTES}

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/layout.module.css
> +  background: white;
давай использовать HEX или RGB

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/layout.test.tsx
> +describe('Note Component', () => {
просьба переименовать в соответствии с содержимым

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/layout.test.tsx
> +      pathname: '/contributors/gleb/notes',
можно брать из констант я полагаю

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +NoteList.getLayout = function getLayout(page: typeof NoteList) {
const getLayout = (page: typeof NoteList): JSX.Element => (<Layout>{page}</Layout>);
NoteList.getLayout = getLayout;

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +            <Note note={note} key={note} />
key={note} - антипаттерн
как минимум стоит сделать
{noteList.map((note, index) => (
  <Note note={note} key={`note_${index + 1}`} />

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +  const image = picture.url ? (
если это компонент, то он Image, а не image

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/imageLoader.ts
> +  return src;
я думаю что чтобы не падало
const imageLoader = ({ src }: { src: string }) => src || '';

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/imageLoader.ts
> +  return src;
или
src || FALLBACK_SRC

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +        <h1 data-testid='title'>Astronomy picture of the day</h1>
data-testid='title' - title может быть где угодно в приложении, нужно уточнять, например picture-title

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +Picture.getLayout = function getLayout(page: typeof Picture) {
может все таки стрелочная функция?

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +          <iframe id='video' title='video' loading='lazy' width='500' height='500' src={picture.url}></iframe>
стоит добавить комментарий что если приходит ссылка с видео - оно гарантировано с ютуба, и этот маневр нужен для совместимости

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +        {picture.media_type !== 'video' ? (
Правилом хорошего кода считается, всегда использовать выражения от позитивной логики. Т.е. picture.media_type === 'video' и так строить логику приложения. В негативных сценариях очень легко уйти в глубину "не не не не не не равно" и тд
+ медиа тайпы хорошо бы в константы запихать

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +const Picture = () => {
не Picture, а PictureLayout или PicturePage

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.module.css
> +.main {
не main, а content какой нить

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.module.css
> +.xz {
это что?)

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.module.css
> +.picture {
рекомендую либо подключить postcss, либо селекторы добавлять по порядку усложнения т.е.
не
picture_title
picture

а

picture
picture_title

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.module.css
> +.picture {
+ picture это избыточно и не отражает смысла
либо picture_image
либо picture_content
мне больше нравится content

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.test.tsx
> +const mockData = {
эти данные обязательно, нужно типизировать - т.е. импортировать типы соответствующего интерфейса стора -
например const mockData: IPictureStoreData = {

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/Picture.tsx
> +// export const getStaticProps = () => {
кстати, либо раскомментируем, либо убираем

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/request.ts
> +      method: 'get',
method лучше писать в апперкейсе GET, POST, PUT, DELETE - стандарт всё же

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/request.ts
> +      url: 'https://api.nasa.gov/planetary/apod?api_key=musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a',
api.nasa.gov - тянуть из констант
api_key=musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a' должен тянуться из .env 
https://nextjs.org/docs/basic-features/environment-variables - see

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/saga-load-data.ts
> +    console.log(error);
error нужно в стор прокидывать, и возможно выводить (это по желанию)

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/saga-load-data.ts
> +    console.log(error);
как пример

function* loginFlow(loginAction: { payload: IUserAuthProps }): SagaIterator {
  try {
    yield put(userActions.setIsLoading(true));
    const authData = loginAction.payload;
    yield call(loginRequest, authData.username, authData.password);
    sessionStorage.setItem('mms_username', authData.username);
    yield put(userActions.setIsLoading(false));
    goHome();
  } catch (error: any) {
    yield put(userActions.setIsLoading(false));
    yield put(userActions.setUserError(error as Error));
  }
}

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/slice.ts
> +      return { ...state, ...pictureData };
это лишнее - редакс тулкит не так работает

2021-11-11 12:05 UTC, Snoopyk8411 commented on src/store/gleb/slice.ts
> +      return { ...state, ...pictureData };
state.picture = action.payload

2021-11-17 07:39 UTC, GlebShulga commented on jest.config.mjs
> +  moduleDirectories: ["node_modules", "src"]
fixed

2021-11-17 07:43 UTC, GlebShulga commented on src/hooks/use-app-selector.ts
> +
fixed

2021-11-17 07:43 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +type Props = {
fixed

2021-11-17 07:44 UTC, GlebShulga commented on src/layout/gleb/components/picture/Picture.tsx
> +// export const getStaticProps = () => {
fixed. Добавлен getStaticProps для первой загрузки данных с API

2021-11-17 07:44 UTC, GlebShulga commented on src/store/gleb/request.ts
> +      method: 'get',
fixed

2021-11-17 07:44 UTC, GlebShulga commented on src/store/gleb/saga-load-data.ts
> +    console.log(error);
fixed

2021-11-17 15:54 UTC, GlebShulga commented on src/layout/gleb/components/note-list/Note-list.tsx
> +NoteList.getLayout = function getLayout(page: typeof NoteList) {
fixed

2021-11-18 09:03 UTC, Beljar commented on next.config.mjs
> +    apiKey: 'musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a',
Ключи и токены обычно не хранят в хранилище по соображениям безопасности

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const el = useRef<HTMLInputElement>(null);
null можно опустить

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (showDatePicker && el && !(el as any).current.contains(e.target)) {
el всегда true, его можно не проверять, а вот наличие значения у поля current у el я бы проверил
any надо убирать

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +export function DatePicker(props: DateProps) {
тип возвращаемого значения?

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const getDateFromDateString = (dateValue: any) => {
any
тип возращаемого значения?

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateData = dateValue.split('-').map((d: string) => parseInt(d, 10));
возможно, безопаснее и удобнее прогонять дату через new Date(dateValue), затем оттуда доставать параметры методами getYear(), getMonth() и т.д.

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/helpers.ts
> +export const getDateStringFromTimestamp = (timestamp: string) => {
тип возвращаемого значения?

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/interfaces.ts
> +import * as Redux from 'redux';
меня уже поругали за такие импорты, передаю эстафету

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/picture/_Picture_._tsx
> +// import Image from 'next/image';
какой-то целиком закоменченный файл? Я не понял, зачем он нужен

2021-11-18 09:03 UTC, Beljar commented on src/pages/contributors/gleb/index.tsx
> +  const res = await fetch(API_URL);
там есть библиотека axios в зависимостях для фетчинга

2021-11-18 09:03 UTC, Beljar commented on src/pages/contributors/gleb/index.tsx
> +  const res = await fetch(API_URL);
надо как-то обрабатывать ошибки фетчинга

2021-11-18 09:03 UTC, Beljar commented on src/store/gleb/request.ts
> +    .then(res => res.data);
.catch(...)

2021-11-18 09:03 UTC, Beljar commented on src/store/gleb/saga-load-data.ts
> +  } catch (error: any) {
error: Error

2021-11-18 09:03 UTC, Beljar commented on src/layout/gleb/components/date-picker/helpers.ts
> +  return dateObject.getFullYear() + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);
там есть src/tools/formatters/, я думаю надо все форматтеры туда валить. И функция addLeadingZero там же есть

2021-11-18 11:17 UTC, Beljar commented on src/store/gleb/saga-load-data.ts
> +  } catch (error: any) {
Тут я не прав был. Можно просто any убрать.

2021-11-18 13:47 UTC, Snoopyk8411 commented on next.config.mjs
> +    apiKey: 'musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a',
мы же обсуждали же, что переменные окружения вроде как должны быть в .env файле или тип того

2021-11-18 13:48 UTC, Snoopyk8411 commented on src/code-style.md
> +Please, use useAppSelector hook from hooks/use-app-selector instead of useSelector as it correctly typed utility.
https://github.com/Snoopyk8411/nbbp-fe/pull/5#pullrequestreview-809727133 - Ивану потом надо будет напомнить об этом

2021-11-18 14:38 UTC, GlebShulga commented on next.config.mjs
> +    apiKey: 'musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a',
fixed.

2021-11-18 15:37 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (showDatePicker && el && !(el as any).current.contains(e.target)) {
fixed

2021-11-18 16:21 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const getDateFromDateString = (dateValue: any) => {
fixed any

2021-11-18 16:24 UTC, GlebShulga commented on src/layout/gleb/components/picture/_Picture_._tsx
> +// import Image from 'next/image';
deleted

2021-11-18 17:15 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +  const res = await fetch(API_URL);
fixed

2021-11-18 17:34 UTC, GlebShulga commented on src/store/gleb/request.ts
> +    .then(res => res.data);
fixed

2021-11-18 17:34 UTC, GlebShulga commented on src/store/gleb/saga-load-data.ts
> +  } catch (error: any) {
fixed

2021-11-18 17:59 UTC, Snoopyk8411 requested changes

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    setTitle(e.target.value);
всё ещё не исправлено

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    setIsError(false);
выглядит избыточно
1) как минимум стоит проверять есть ли вообще ошибка
if (isError) setIsError(false)

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +      setIsError(true);
как я уже говорил ранее, else здесь избыточно. а присвоение true/false в явном виде - скорее всего говорит об не эффективном использовании переменных
в данном случае:

const handleClickAddNote = () => {
    if (isTitleLengthValid) {
      addNote(title);
      setTitle(EMPTY_STRING);
    }
    setIsError(!isTitleLengthValid);
}

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/Create-note.tsx
> +import { ENTER_BUTTON, EMPTY_STRING } from 'constants/constants';
зачем заводить в папке constants - файл constants? выглядит неэффективно.
index.ts более чем подходит. - если хотите разбивать константы по файлам, а в index.ts их допустим собирать, то тоже файл с именем constants не выглядит качественным

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/create-note/create-note.module.css
> +  background-color: white
а white как просочился? 
1) явно white должен быть в константах
2) договорились же использовать RGB

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const el = useRef<HTMLInputElement>(null);
ну это уж совсем вкусовщина

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const inputRef: RefObject<HTMLInputElement> = createRef();
тебе правда здесь нужно и useRef и createRef?
я че то не вижу смысла
https://stackoverflow.com/questions/54620698/whats-the-difference-between-useref-and-createref

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const inputRef: RefObject<HTMLInputElement> = createRef();
тем более ниже ты используешь рефу ровно как useRef

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const el = useRef<HTMLInputElement>(null);
требуется переименовать рефу на более декларативную - невозможно понять что это и для чго

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (showDatePicker && el && !(el as any).current.contains(e.target)) {
1) el as any - непорядок, если он ругается на current - значит расширяем тип MouseEvent
2) el && !(el as any).current.contains(e.target) - должно быть вынесено в отдельную декларативную константу
например const targetIsNotComponentPart
3) затем, для if нужно сделать отдельную переменную
например const datePickerMustBeUnshown = showDatePicker && targetIsNotComponentPart

и затем использовать:

if (datePickerMustBeUnshown) setShowDatePicker(false);

4) addBackDrop - совершенно не соответствует содержанию функции - это самое некорректное что можно сделать - назвать функцию без соответствия её содержанию. Функцию нужно переименовать, либо пересмотреть логику

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    //  Only needed when using SSR in Next.js
и зачем здесь эти комментарии?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (inputRef.current) inputRef.current.value = dateString;
непонятно зачем ты напрямую через dom задаешь значение инпуту - это обходной путь, для решения задач, когда действительно нужен именно dom element.
В твоем случае, это должен быть просто контролируемый инпут ( см controlled input react)

т.е. в этом месте ты должен был бы использовать setDate сделанный из setState, а date - должен быть использован инпутом
value={date} или как то так

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    props.onChange(selectedDay);
все props - мы деструктурируем в начале компонента + указываем их в IProps + если они не обязательные - нужна проверка

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const selectedDay: string = new Date(dateData.year, dateData.month - 1, dateData.date + 1)
если тебе нужен именно day - то есть специальный метод у date - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate

в ином случае, стоит переименовать переменную

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const getDateFromDateString = (dateValue: any) => {
отсутствуют типы

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const getDateFromDateString = (dateValue: any) => {
и этой функции стоит находится в helpers ts по соседству, так как это самая что ни на есть - утилита

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateData = dateValue.split('-').map((d: string) => parseInt(d, 10));
согласен + мы не используем сокращения

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (dateData.length < 3) {
что за мистическое условие? оно должно быть в декларативной понятной константе

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const year = dateData[0];
эти три строчки можно заменить на 1 деструктуризацию ( см array destructuring )

const [year, month, date] = dateData

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    return { year, month, date };
здесь подозрительно мало типизации

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateValue = inputRef.current?.value;
абсолютно непонятный и не верный с точки зрения реакт подход.
Здесь должен быть event.target и тд и тп, никакие рефы тут не нужны

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/helpers.ts
> +export const getDateStringFromTimestamp = (timestamp: string) => {
очень похоже на то что ты использовал в Date picker - похоже что где-то дублирование, дублирования быть не должно

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/helpers.ts
> +  return dateObject.getFullYear() + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);
совершенно согласен, функции форматтеры есть и думаю, что они покрывают то, что здесь требуется, но если не полностью - то их стоит добавлять туда

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/interfaces.ts
> +export interface IDateData {
интерфейс есть, но по месту почему то не используется.
Дополнительно, в тайпскрипте есть отдельный тип Date

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/error/Error.tsx
> +          <div>The note length must not be shorter than 3 characters</div>
если это текст, то почему div, а не p например? https://htmlacademy.ru/courses/299/run/12

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/error/Error.tsx
> +          <div>The note length must not be shorter than 3 characters</div>
http://htmlbook.ru/html/p

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/interfaces.ts
> +import * as Redux from 'redux';
все верно - данный код избыточен))))

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +import { ReactNode } from 'react';
почему файл называется layout.tsx?) что за не любовь к index.tsx?))

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +import { ReactNode } from 'react';
ну в импортах масло масляное получается :C

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/layout.module.css
> +  background: white;
still и не константы и не RGB

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +import CreateNote from 'layout/gleb/components/create-note/Create-note';
вот во всех трех импортах
1) мы договорились с умом использовать export default а не вообще везде
2) зачем /create-note/Create-note ? для того чтобы в vs code удобнее было?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +    setNoteList([note, ...noteList]);
а ещё лучше было бы сделать
const updatedNoteList = [note, ...noteList];
setNoteList(updatedNoteList);

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +export default NoteList;
зачем дефолтные экспорты?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/note-list.module.css
> +  height:100%
тут пробел и точка с запятой отсутствуют

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/note-list.module.css
> +  margin-left: 1.5rem
тут точка с запятой - перепроверить все css'ки

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/note-list.test.tsx
> +  it('NoteList snapshot', () => {
мб все таки it('makes NoteList snapshot') - ? ну чтобы нативно звучало, или как?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/note/Note.tsx
> +const Note: React.FC<NoteProps> = ({ note }) => {
Сильный компонент безусловно - а почему не стилизован?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/_Picture_._tsx
> +// import Image from 'next/image';
присоединяюсь

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/imageLoader.ts
> +const imageLoader = ({ src }: { src: string }) => src || '';
а возвращаемый тип почему забываем?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.test.tsx
> +const mockData = {
типизация так и не подьехала

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/welcome/index.tsx
> +        <div>{/* <img src='assets/vercel.svg' /> */}</div>
это зачем закомментированно?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/layout/welcome/index.tsx
> +            {/* <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} /> */}
И это - если оно не нужно - выпиливаем и всё

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +  const picture = isToday ? todayPicture : pictureFromStore;
давай держать порядок - очевидно эту переменную стоит держать рядом с обьявлением других переменных и перед хуками и компонентами

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +const PicturePage: IPicturePageType = ({ todayPicture }) => {
здесь всё очень странно с неймингами - из-за этого непонятно логика компонента

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +  const pictureFromStore = useAppSelector(pictureSelector);
если это картинка из стора - то это storedPicture

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +  const onChange = (newDate: string) => setDate(newDate);
1) не onChange, а handleChange
2) отсутствует возвращаемый тип

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +    if (date !== pictureFromStore.date) {
логика компонента не понятна.
что такое isToday? и что тогда лежит в storedPicture?
зачем мы сравниваем date?

максимально не хватает декларативных переменных

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +    if (date !== pictureFromStore.date) {
isToday надо вообще убрать. Если я правильно понял идею
1) у тебя в сторе есть какая то пикча - по умолчанию она свежая и равна предвыбранной дате
2) тогда не todayPicture, а fetchedPicture приходит в пропсах видимо.
3) поскольку дальше похоже что ты запрашиваешь картинку и ты тянешь её уже из стора всегда
4) тогда не fetchedPicture, а initialPicture или initiallyFetchedPicture
5) тогда не pictureFromStore, а просто picture - считается хорошим тоном и правильным именовать пропсы в компоненты также как их отражения в сторе
6) тогда не const picture = isToday ? todayPicture : pictureFromStore;
а const targetPicture = isDateInitial ? initiallyFetchedPicture : picture;
7) тогда не if (date !== pictureFromStore.date) {
а
const isNewDateSelected = date !== picture.date;
if (isNewDateSelected) {
setIsInitialDateSelected(date === initiallyFetchedPicture.date);

---
8) но опять же неувязочка, у тебя есть префетченная picture, приходит она из getStaticProps
далее все работает со стором и запросом картинок. Вероятно, в такой ситуации, нужно выправить flow, а именно на componentDidMount записать в стор initiallyFetchedPicture, если её там нет уже.
Если ты подумаешь про то, что префетченная картинка в текущей реализации у тебя всегда сохранена засчет замыкания, то я тебе отвечу - во первых не очень хорошо так замыкания использовать, а во вторых можно отдельное место в сторе завести для initiallyFetched

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +    <Image loader={imageLoader} unoptimized src={picture.url} alt={picture.title} width='800px' height='600px' />
1) width  и height можно и тэгу img задать
2) почему компонент Image не стилизован, а img стилизован?
3) зачем нам использовать или то или другое?
3.1) Если это из-за какого то мистического падения Image - то надо прогуглить из-за чего оно и как это поведение исправляют
3.2) и тогда поменять тернарник на что-то что описывает причины разветвления, такой ответ на вопрос "зачем здесь вариативность компонент?"
3.3) в текущих реалиях это должно выглядеть так
const isSrcNotFallable = !!picture.url;
const image = isSrcNotFallable ? ( ...

4) далее, как я и говорил, не очень хорошо использовать обращение к обьекту повсюду
src={picture.url} alt={picture.title}

вместо этого мы деструктурируем свойства и их используем

const {
url, title, media_type, explanation,
} = picture;

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +        {picture.media_type === VIDEO ? (
picture.media_type === VIDEO - это не явное условие, нужно выносить в декларативные флаги
const isContentTypeVideo = picture.media_type === VIDEO

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +        {picture.media_type === VIDEO ? (
ты спросишь почему content? потому что picture не бывает video, если у тебя что-то либо картинка либо video - то это уже контент, либо media (этот вариант предпочтительнее)

Следовательно надо все переименовать в media, начиная с переменных и заканчивая viewMediaPage <- это самое точное и правильное наименование данной страницы

либо же mediaPickPage

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +  const res = await fetch(API_URL);
копипасту всегда нужно дорабатывать...
для фетчей мы используем axios и действительно ошибки нужно обрабатывать - например, отдавать fallback изображение (которое нужно сперва сделать)

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/helpers.ts
> +const oneDay = SECOND_IN_MILLIS * MINUTE_IN_SECONDS * HOUR_IN_MINUTES * DAY_IN_HOURS;
это конечно сурово) но в данном случае можно было и без констант - данные числа конвертации знают все)

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/request.ts
> +  console.log();
консоль лог

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/request.ts
> +    .then(res => res.data);
согласен

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/saga-load-data.ts
> +    const newDate: DateSelectorReturn = yield select(selectDate);
а почему лоадер нигде не предусмотрен?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/selectors.ts
> +export const selectNewDateFromDatePicker = createSelector(selectDateFromDatePicker, state => state);
бесполезный селектор

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/slice.ts
> +    date: date.toISOString().slice(0, 10),
зачем это мистическое преобразование? оно должно быть вынесено в функцию с понятным названием и скорее всего, если это отрезка timezone - эта функция уже есть в tools

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/gleb/slice.ts
> +      return { ...state, picture: { ...state.picture, date } };
читаем документацию кита, как им правильно пользоваться

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/index.ts
> +import { rootReducer } from './reducers';
это что-то странное просочилось - так не должно быть
см // ./reducers.ts
export default rootReducer;

должно оставаться как было

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/reducers.ts
> +export const rootReducer = combineReducers({
зачем?

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/sagas.ts
>    yield all([wpLoadInitDataWatcher()]);
можно перед тем как делать, прочитать как это работает?
yield all([
wpLoadInitDataWatcher(),
mtLoadDataWatcher()
]);

2021-11-18 17:59 UTC, Snoopyk8411 commented on src/store/sagas.ts
> +import mtLoadDataWatcher from './gleb/saga-load-data';
имя файла саги, и имя вотчера должны быть изменены и и быть логичным продолжением названия генератора  - в твоем случае : 
export default function* getMediaByDateWatcher(): Generator {
  yield takeEvery(actions.getMediaByDate, getMediaByDateFlow);
}

function* getMediaByDateFlow(action: { payload: ... }): SagaIterator { ...

или в том же духе

2021-11-18 18:02 UTC, Beljar approved these changes

2021-11-19 05:36 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    setIsError(false);
fixed

2021-11-19 05:37 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +import { ENTER_BUTTON, EMPTY_STRING } from 'constants/constants';
renamed folder 'constants/constants' to 'constants/index'

2021-11-19 05:44 UTC, GlebShulga commented on src/layout/gleb/components/create-note/create-note.module.css
> +  background-color: white
fixed

2021-11-19 06:22 UTC, GlebShulga commented on src/store/gleb/slice.ts
> +      return { ...state, picture: { ...state.picture, date } };
fixed

2021-11-19 06:29 UTC, GlebShulga commented on src/store/reducers.ts
> +export const rootReducer = combineReducers({
Думал, что нужно везде нужно убирать дефолтные экспорты. Вернул как было

2021-11-19 06:29 UTC, GlebShulga commented on src/store/index.ts
> +import { rootReducer } from './reducers';
fixed

2021-11-19 06:36 UTC, GlebShulga commented on src/store/sagas.ts
>    yield all([wpLoadInitDataWatcher()]);
Почитал. Fixed

2021-11-19 06:36 UTC, GlebShulga commented on src/store/sagas.ts
> +import mtLoadDataWatcher from './gleb/saga-load-data';
fixed

2021-11-19 09:49 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const inputRef: RefObject<HTMLInputElement> = createRef();
Отрефакторил компонент Date-picker. Убрал useRef и лишние функции

2021-11-19 09:51 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const el = useRef<HTMLInputElement>(null);
deleted

2021-11-19 10:02 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    //  Only needed when using SSR in Next.js
deleted

2021-11-19 10:23 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const getDateFromDateString = (dateValue: any) => {
deleted

2021-11-19 10:23 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const selectedDay: string = new Date(dateData.year, dateData.month - 1, dateData.date + 1)
deleted

2021-11-19 10:23 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    props.onChange(selectedDay);
fixed

2021-11-19 10:23 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (inputRef.current) inputRef.current.value = dateString;
fixed

2021-11-19 10:24 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateData = dateValue.split('-').map((d: string) => parseInt(d, 10));
deleted

2021-11-19 10:24 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (dateData.length < 3) {
deleted

2021-11-19 10:24 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const year = dateData[0];
deleted

2021-11-19 10:24 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    return { year, month, date };
deleted

2021-11-19 10:25 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateValue = inputRef.current?.value;
fixed

2021-11-19 10:27 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/helpers.ts
> +export const getDateStringFromTimestamp = (timestamp: string) => {
Удалил дубль в Date picker

2021-11-19 10:57 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/helpers.ts
> +  return dateObject.getFullYear() + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);
Использовал уже готовую addLeadingZero

2021-11-19 11:20 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    setTitle(e.target.value);
Переписал на const value = e?.target?.value ?? ''

2021-11-19 11:38 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    const dateData = dateValue.split('-').map((d: string) => parseInt(d, 10));
deleted

2021-11-22 05:21 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +      setIsError(true);
fixed

2021-11-22 05:22 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/helpers.ts
> +export const getDateStringFromTimestamp = (timestamp: string) => {
fixed

2021-11-22 05:22 UTC, GlebShulga commented on src/layout/gleb/components/interfaces.ts
> +import * as Redux from 'redux';
fixed

2021-11-22 05:23 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +export function DatePicker(props: DateProps) {
fixed

2021-11-22 05:23 UTC, GlebShulga commented on src/store/gleb/slice.ts
> +      return { ...state, ...pictureData };
fixed

2021-11-22 05:24 UTC, GlebShulga commented on src/store/gleb/request.ts
> +      url: 'https://api.nasa.gov/planetary/apod?api_key=musopXnASrDXLrAcjqs4aSU3Fd9pXF9nYnFsCh5a',
fixed

2021-11-22 05:34 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const [error, setError] = useState(false);
fixed

2021-11-22 05:34 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const [title, setTitle] = useState('');
fixed

2021-11-22 05:34 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const onClickaddNote = () => {
fixed

2021-11-22 05:34 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +    if (title.length <= 20 && title.length >= 3) {
fixed

2021-11-22 05:35 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          rows={3}
fixed

2021-11-22 05:35 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          placeholder='Write new note'
fixed

2021-11-22 05:35 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +          <button type='button' onClick={onClickaddNote} className={styles.addNoteButton__disabled} disabled>
fixed

2021-11-22 05:35 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +      {error && (
done

2021-11-22 05:36 UTC, GlebShulga commented on src/layout/gleb/components/create-note/create-note.module.css
> +  margin: 20px 0;
fixed

2021-11-22 15:01 UTC, Snoopyk8411 requested changes

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  let dateValue;
вот это лишняя переменная

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const [isDatePickerShown, setIsDatePickerShown] = useState(false);
я не понимаю зачем здесь эта переменная - она туда-сюда гоняется, но не влияет на рендер совершенно - и никуда не прокидывается. Получается что и на лишняя. Либо здесь не хватает компонента, который в зависимости от этой переменной отрисовывался либо нет

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +      setDateInsideComponent(dateValue);
в целом setDateInsideComponent - не нужна: её название не соответствует её функционалу
либо переименовать в че-нить типо updateDate, либо как по мне стоит просто убрать данную функцию, а
dispatch(setData(dateValue));
    /** Pass data to parent */
    onChange(dateValue);
перенести сюда

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (inputRef.current) inputRef.current.value = dateString;
все равно не понимаю, зачем здесь это

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/date-picker.test.tsx
> +const mockData = {
отсутствует тип

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/date-picker/helpers.ts
> +  return dateObject.getFullYear() + '-' + addLeadingZero(month) + '-' + addLeadingZero(date);
странный всё же формат - если такой нужен в API - то это надо данные ре-маппить прямо перед отправкой, а не хранить их в таком виде

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/error/Error.tsx
> +          <div>The note length must not be shorter than 3 characters</div>
ответа нет

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +import { ReactNode } from 'react';
ответа нет

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +import styles from './layout.module.css';
договорились что импортируем стили с привязкой к контексту - не просто styles
а какой-нибудь layoutStyles

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +import CreateNote from 'layout/gleb/components/create-note/Create-note';
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +    setNoteList([note, ...noteList]);
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/Note-list.tsx
> +export default NoteList;
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/note-list/note-list.test.tsx
> +  it('NoteList snapshot', () => {
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/note/Note.tsx
> +const Note: React.FC<NoteProps> = ({ note }) => {
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/imageLoader.ts
> +const imageLoader = ({ src }: { src: string }) => src || '';
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/layout/gleb/components/picture/picture.test.tsx
> +const mockData = {
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +  const onChange = (newDate: string) => setDate(newDate);
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/pages/contributors/gleb/index.tsx
> +        {currentPicture.media_type === VIDEO ? (
писал же уже ранее, если может быть media_type не картинка, значит это уже не currentPicture, а currentMedia - и этот факт должен повлиять на все местные обозначения

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/store/gleb/request.ts
> +  console.log();
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/store/gleb/saga-load-data.ts
> +    const newDate: DateSelectorReturn = yield select(selectDate);
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/store/gleb/selectors.ts
> +export const pictureSelector = createSelector(selectPicture, state => state);
и этот тоже бесполезный

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/store/gleb/selectors.ts
> +export const selectNewDateFromDatePicker = createSelector(selectDateFromDatePicker, state => state);
нет ответа

2021-11-22 15:01 UTC, Snoopyk8411 commented on src/store/gleb/slice.ts
> +    date: date.toISOString().slice(0, 10),
нет ответа

2021-11-22 15:25 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  const [isDatePickerShown, setIsDatePickerShown] = useState(false);
deleted

2021-11-22 15:34 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/date-picker.test.tsx
> +const mockData = {
fixed

2021-11-22 15:43 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +      setDateInsideComponent(dateValue);
Переименовал функцию в updateDate

2021-11-22 18:20 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +        {currentPicture.media_type === VIDEO ? (
fixed

2021-11-23 08:29 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/interfaces.ts
> +export interface IDateData {
deleted

2021-11-23 08:35 UTC, GlebShulga commented on src/layout/gleb/components/error/Error.tsx
> +          <div>The note length must not be shorter than 3 characters</div>
Заменил **div** на **p**

2021-11-23 09:20 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +    if (inputRef.current) inputRef.current.value = dateString;
fixed

2021-11-23 09:26 UTC, GlebShulga commented on src/layout/gleb/components/note-list/Note-list.tsx
> +import CreateNote from 'layout/gleb/components/create-note/Create-note';
1. fixed
2. Чтобы не запутаться в index.tsx которые будут в каждой папке.

2021-11-23 09:27 UTC, GlebShulga commented on src/layout/gleb/components/note-list/Note-list.tsx
> +    setNoteList([note, ...noteList]);
fixed

2021-11-23 09:28 UTC, GlebShulga commented on src/layout/gleb/components/note-list/Note-list.tsx
> +export default NoteList;
fixed

2021-11-23 09:32 UTC, GlebShulga commented on src/layout/gleb/components/note-list/note-list.module.css
> +  height:100%
fixed

2021-11-23 09:33 UTC, GlebShulga commented on src/layout/gleb/components/note-list/note-list.module.css
> +  margin-left: 1.5rem
fixed во всех css файлах

2021-11-23 09:34 UTC, GlebShulga commented on src/layout/gleb/components/note-list/note-list.test.tsx
> +  it('NoteList snapshot', () => {
Переименовал во всех тестах со snapshot'ами

2021-11-23 09:35 UTC, GlebShulga commented on src/layout/gleb/components/note/Note.tsx
> +const Note: React.FC<NoteProps> = ({ note }) => {
Он хорош сам по себе без стилей :)

2021-11-23 09:38 UTC, GlebShulga commented on src/layout/gleb/components/picture/imageLoader.ts
> +const imageLoader = ({ src }: { src: string }) => src || '';
fixed

2021-11-23 09:38 UTC, GlebShulga commented on src/layout/welcome/index.tsx
> +        <div>{/* <img src='assets/vercel.svg' /> */}</div>
deleted

2021-11-23 09:38 UTC, GlebShulga commented on src/layout/welcome/index.tsx
> +            {/* <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} /> */}
deleted

2021-11-23 09:39 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +  const picture = isToday ? todayPicture : pictureFromStore;
fixed

2021-11-23 09:40 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +const PicturePage: IPicturePageType = ({ todayPicture }) => {
Переименовал Picture в Media, todayPicture в  initialMedia и т. д.

2021-11-23 09:45 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +  const pictureFromStore = useAppSelector(pictureSelector);
Переименовал в storedMedia

2021-11-23 09:53 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +  const onChange = (newDate: string) => setDate(newDate);
1. Переименовал
2. Добавил возвращаемый тип

2021-11-23 09:56 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +    if (date !== pictureFromStore.date) {
Порефакторил. Посмотри, пожалуйста, ещё раз.

2021-11-23 10:00 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +    <Image loader={imageLoader} unoptimized src={picture.url} alt={picture.title} width='800px' height='600px' />
- Выпилил тег img, оставил только компонент Image и проверку на наличие url.
- Сделал деструктуризацию свойств picture (теперь это currentMedia)

2021-11-23 10:03 UTC, GlebShulga commented on src/pages/contributors/gleb/index.tsx
> +        {picture.media_type === VIDEO ? (
- Добавил флаг isMediaTypeVideo
- Переименовал все picture в media.

2021-11-23 10:03 UTC, GlebShulga commented on src/store/gleb/request.ts
> +  console.log();
deleted

2021-11-23 11:03 UTC, GlebShulga commented on src/store/gleb/saga-load-data.ts
> +    const newDate: DateSelectorReturn = yield select(selectDate);
Добавил loader

2021-11-23 11:04 UTC, GlebShulga commented on src/store/gleb/selectors.ts
> +export const selectNewDateFromDatePicker = createSelector(selectDateFromDatePicker, state => state);
отрефакторил

2021-11-23 11:18 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/Date-picker.tsx
> +  let dateValue;
Переписал использование переменных в компоненте.

2021-11-23 11:21 UTC, GlebShulga commented on src/layout/gleb/components/date-picker/helpers.ts
> +  return dateObject.getFullYear() + '-' + addLeadingZero(month) + '-' + addLeadingZero(date);
deleted

2021-11-23 11:28 UTC, GlebShulga commented on src/layout/gleb/components/layout/Layout.tsx
> +import styles from './layout.module.css';
Насколько я понял style - это служебное слово для импорта стилей в Next.js и изменить его нельзя. 
![Screenshot 2021-11-23 142644](https://user-images.githubusercontent.com/67621167/143016317-b5b9394d-91f2-47d4-93a6-637f9853130d.png)

2021-11-23 11:32 UTC, GlebShulga commented on src/store/gleb/selectors.ts
> +export const pictureSelector = createSelector(selectPicture, state => state);
fixed

2021-11-23 12:07 UTC, GlebShulga commented on src/layout/gleb/components/create-note/Create-note.tsx
> +  const onChangeNote = (e: ChangeEvent<HTMLTextAreaElement>) => {
fixed

2021-11-23 12:13 UTC, GlebShulga commented on src/layout/gleb/components/create-note/create-note.module.css
> +  color: #1f2937;
rgb в константах

2021-11-23 12:47 UTC, Snoopyk8411 approved these changes

2021-11-23 12:47 UTC, Snoopyk8411 commented on src/layout/gleb/components/layout/Layout.tsx
> +import styles from './layout.module.css';
вполне можно) в соседних ПР меняли и все работало) в этом и суть абсолютного импорта, что можно переименовать как угодно

2021-11-23 14:55 UTC, merged