Feature/nbpp 9 contrib page
Snoopyk8411/nbbp-fe pull request #5
Opened 2021-11-15 07:12 UTC by py-cs

2021-11-16 06:02 UTC, GlebShulga commented on src/layout/contributors/ivanefimov/components/card/card.module.css
> +  --clr-accent-400: hsl(140, 90%, 61%);
Вроде договаривались выносить все переменные с цветами в globals.css

2021-11-16 06:02 UTC, GlebShulga commented on src/layout/contributors/ivanefimov/components/card/card.module.css
> +  padding: 160px 0 0;
Так px или rem?

2021-11-16 06:02 UTC, GlebShulga commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import { getUrlById } from '../../helpers';
Договорились указывать абсолютные пути -> layout/contributors/ivanefimov/helpers

2021-11-16 06:02 UTC, GlebShulga commented on src/store/contributors/ivanefimov/slice.ts
> +export const { actions } = galleryPageSlice;
Проще сделать декстуртуризацию и не нести **actions** в компоненты. 
export const { fetchPage, addPage, setNextPage, setHasMore, setError, setIsLoading} = galleryPageSlice.actions;

2021-11-16 06:02 UTC, GlebShulga commented on src/layout/contributors/ivanefimov/gallery.tsx
> +import { actions } from 'store/contributors/ivanefimov/slice';
Следует сделать импорт контректных action'ов после их деструктуризации при экспорте из store/contributors/ivanefimov/slice.ts

2021-11-16 06:02 UTC, GlebShulga commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
Для изображений в  Next.js лучше использовать компонент <Image>.
https://nextjs.org/docs/basic-features/image-optimization

2021-11-17 05:55 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.module.css
> +  --clr-accent-400: hsl(140, 90%, 61%);
Пока раздельные страницы, персональные переменные держу внутри.

2021-11-17 05:57 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.module.css
> +  padding: 160px 0 0;
Пока общие глобальные стили не (включая font-size на html) не заведены, надежнее пиксели внутри своих компонентов.

2021-11-17 05:58 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import { getUrlById } from '../../helpers';
Абсолютные пути почему-то валят тесты. Надо разбираться.

2021-11-17 06:00 UTC, py-cs commented on src/store/contributors/ivanefimov/slice.ts
> +export const { actions } = galleryPageSlice;
Исправлено

2021-11-17 06:04 UTC, py-cs commented on src/layout/contributors/ivanefimov/gallery.tsx
> +import { actions } from 'store/contributors/ivanefimov/slice';
Исправлено

2021-11-17 06:06 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
Предполагается, что изображение открывается для скачивания в полном размере. Оптимизации, включая уменьшение размера до размера вьюпорта не нужны.

2021-11-18 13:44 UTC, Snoopyk8411 requested changes

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import { getUrlById } from '../../helpers';
не валят - всё должно работать

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import styles from './card.module.css';
договорились называть не styles, а cardStyles в данном случае

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/gallery.tsx
> +    if (!isLoading && hasMore && isEndOfPage) {
здесь стоит, как и в любом if else condition, загонять условия в некоторый декларативный флаг
например
const isFetchNextPageRequired = !isLoading && hasMore && isEndOfPage;
и затем использовать как
if (isFetchNextPageRequired) { ...

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/gallery.tsx
> +          {[...initialPhotos, ...photos].map(photo => (
этот подход не корректен с точки зрения потока данных - получается ты каждый раз прокидываешь АБСОЛЮТНО НОВЫЙ массив, так как делаешь свежую копию с помощью спред оператора.
Точно не уверен, но предполагаю, что это ломает все оптимизации реакта с использованием ключей, так как он считает что ему каждый раз пришел абсолютно новый набор данных.

Правильный алгоритм:
1) с помощью useState - сделать локальный стейт с initialPhotos - его и использовать.
2) когда приходят новые photos с помощью useEffect - обновлять photos
3) в рендере использовать эти самые photos из setState

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
а lazy load не нужен?

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/pages/contributors/ivanefimov/[id].tsx
> +interface IFullSizePhotoProps {
мы в папке pages - значит это, вероятно FullSizePhotoPage??

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/pages/contributors/ivanefimov/[id].tsx
> +export const getServerSideProps: GetServerSideProps = async ({ params }) => {
почему не указан тип для params?

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
Странная конечно страничка из одной фотографии)

2021-11-18 13:44 UTC, Snoopyk8411 commented on src/store/contributors/ivanefimov/selectors.ts
> +export const selectIsLoading = createSelector(selectGalleryPage, gp => gp.isLoading);
в аргументах функций, как и в других местах - категорически не рекомендовано использовать сокращения - вебпак все равно обфусцирует код как ему надо, а так мы ухудшаем читаемость кода для других разработчиков

2021-11-18 14:05 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import styles from './card.module.css';
исправлено

2021-11-18 14:07 UTC, py-cs commented on src/layout/contributors/ivanefimov/gallery.tsx
> +    if (!isLoading && hasMore && isEndOfPage) {
Исправлено

2021-11-18 14:30 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
Нет, это просто страница для вывода полноразмерного изображения для скачивания, включена для теста динамических маршрутов и получения параметров из адресной строки.

2021-11-18 14:32 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +interface IFullSizePhotoProps {
исправлено

2021-11-18 14:34 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +export const getServerSideProps: GetServerSideProps = async ({ params }) => {
Потому что тип прописан на самой функции. Соответственно у нас типизированы аргументы и возвращаемое значение.

2021-11-18 14:35 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +const FullSizePhoto = ({ photo }: IFullSizePhotoProps): JSX.Element => <img src={photo.download_url} alt={`photo by ${photo.author}`} />;
Так задумано, коммент выше. Это не страница детализации, все данные, что я получаю из api уже в карточках.

2021-11-18 14:35 UTC, py-cs commented on src/store/contributors/ivanefimov/selectors.ts
> +export const selectIsLoading = createSelector(selectGalleryPage, gp => gp.isLoading);
Исправлено

2021-11-18 14:51 UTC, py-cs commented on src/layout/contributors/ivanefimov/gallery.tsx
> +          {[...initialPhotos, ...photos].map(photo => (
Прокидываю пропсы (с сервера), они всегда одинаковые. Подгруженное по прокрутке складываю в стор и использую оттуда.
Т.е. я маплю два массива из объектов (IPhoto).
Насколько я понимаю, есть три варианта, чтобы смапить последовательно два массива:
1. [...propsArr, ...stateArr].map ....
2. propsArr.map .... ; stateArr.map ....
3. [propsArr, stateArr].forEach(arr => arr.map .....)
С ключами, которые реакт использует для reconsilliation во всех вариантах всё будет одинаково, сами объекты тоже будут одни и те же, массивы будут содержать ссылки на те же самые объекты + новая подгруженная пачка).

Первый самый читабельный, второй тоже норм, но с дублированием кода, третий с избыточной вложенностью.

Насчет правильного алгоритма всё так, только есть одно но - стор в этой схеме не нужен вообще. А суть задачи в общем-то в том, чтобы попробовать саги и сср.

2021-11-18 15:03 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import { getUrlById } from '../../helpers';
Исправлено, путь добавлен в конфиг jest

2021-11-18 15:04 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +import styles from './card.module.css';
Исправлено, путь добавлен в конфиг jest, импорт классов переименован.

2021-11-18 15:04 UTC, py-cs commented on src/layout/contributors/ivanefimov/gallery.tsx
> +    if (!isLoading && hasMore && isEndOfPage) {
Исправлено

2021-11-18 18:03 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +          {photo.width} x {photo.height} px
лучше деструктурировать пропсы и не обращаться к обьектам

2021-11-18 18:04 UTC, Snoopyk8411 commented on src/layout/contributors/ivanefimov/gallery.tsx
> +          {initialPhotos.map(photo => (
ну я не это имел в виду, но если тебе так нужно было то ок

2021-11-18 18:08 UTC, Snoopyk8411 requested changes

2021-11-18 18:08 UTC, Snoopyk8411 commented on src/pages/contributors/ivanefimov/[id].tsx
> +export const getServerSideProps: GetServerSideProps = async ({ params }) => {
ничего подобного, если бы это было так
params?.id as string - вот эта строчка не нужна бы была, а раз она нужна - значит ТС не видит из чего состоят params, и уж тем более не видит что ты возвращаешь photo тип которого тоже не указан, да ещё и в обьекте

2021-11-18 18:08 UTC, Snoopyk8411 commented on src/store/contributors/ivanefimov/api-get-photos.ts
> +    .then(res => res.data);
catch блоков нет в axios - не понятно что будет если метод не отработает - вероятно приложение упадёт - нужно предусмотреть такое поведение

2021-11-19 06:21 UTC, py-cs commented on src/pages/contributors/ivanefimov/[id].tsx
> +export const getServerSideProps: GetServerSideProps = async ({ params }) => {
Исправлено

2021-11-19 06:23 UTC, py-cs commented on src/layout/contributors/ivanefimov/components/card/card.tsx
> +          {photo.width} x {photo.height} px
Исправлено

2021-11-19 06:49 UTC, py-cs commented on src/store/contributors/ivanefimov/api-get-photos.ts
> +    .then(res => res.data);
Добавил обработку ошибок в api

2021-11-19 12:42 UTC, Snoopyk8411 approved these changes

2021-11-19 12:43 UTC, merged