feat: add shop page template
Snoopyk8411/nbbp-fe pull request #6
Opened 2021-11-22 13:43 UTC by py-cs

2021-11-23 11:46 UTC, Snoopyk8411 requested changes

2021-11-23 11:46 UTC, Snoopyk8411 commented on src/pages/shop.tsx
> +      <link rel='preconnect' href='https://fonts.googleapis.com' />
а эти три линка нам зачем?

2021-11-23 11:46 UTC, Snoopyk8411 commented on src/pages/shop.tsx
> +        <meta content="" name="yandex-verification" />
и эти

2021-11-23 11:46 UTC, Snoopyk8411 commented on src/layout/shop/index.tsx
> +interface ShopPageLayoutProps {
зачем удалил favicon?

2021-11-23 12:00 UTC, py-cs commented on src/pages/shop.tsx
> +        <meta content="" name="yandex-verification" />
С верификацией яндекс и гугл дают доступ к статистике по индексации. Актуально при деплое, поэтому добавлено, прокомментировано и закомментировано.

2021-11-23 12:06 UTC, py-cs commented on src/layout/shop/index.tsx
> +interface ShopPageLayoutProps {
Иконка заменена, в ветке файл присутствует.

2021-11-23 12:07 UTC, py-cs commented on src/pages/shop.tsx
> +      <link rel='preconnect' href='https://fonts.googleapis.com' />
Стандартное подключение гугл-шрифтов, Лайтхаус тоже рекомендует:
![image](https://user-images.githubusercontent.com/65309358/143021443-5918134d-ea84-4d2e-95a2-c9656f5c8b6b.png)

2021-11-24 06:56 UTC, GlebShulga approved these changes

2021-11-24 06:56 UTC, GlebShulga commented on src/pages/shop.tsx
> +import Head from 'next/head';
Может снести страницу бойлерплейта index в туда положить эту?

2021-11-24 07:43 UTC, py-cs commented on src/pages/shop.tsx
> +import Head from 'next/head';
Обсудили на дейли, оставляем по пути /shop

2021-11-24 11:07 UTC, Snoopyk8411 approved these changes

2021-11-24 11:27 UTC, merged