Feature/nbpp 19 fe link component
Snoopyk8411/nbbp-fe pull request #8
Opened 2021-11-25 14:50 UTC by GlebShulga

2021-11-25 17:07 UTC, Snoopyk8411 requested changes

2021-11-25 17:07 UTC, Snoopyk8411 commented on public/assets/pot.svg
> +<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
кажется вот эту строчку и xml можно смело выпиливать

2021-11-25 17:07 UTC, Snoopyk8411 commented on public/assets/pot.svg
> +	 viewBox="0 0 35.235 35.235" style="enable-background:new 0 0 35.235 35.235;" xml:space="preserve">
а что за enable-background? это для чего?

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/header/header.module.css
> +  transform: translate3d(0, 0, 0);
эт зачем?

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/header/header.module.css
> +  box-shadow: 0px 1px 17px rgb(0 0 0 / 9%);
rgb(0 0 0 / 9%) - это как работает? rgba не поможет в данном случае?

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/link/Link.tsx
> +    if (accent === 1) {
и здесь заменить на enum очевидно

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/link/Link.tsx
> +      {svg && <img src={svg} alt={title} className={linkStyles.svg} />}
а мы разве не можем просто svg как svg элемент использовать? без img?

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/link/Link.tsx
> +      {svg && <img src={svg} alt={title} className={linkStyles.svg} />}
![Снимок экрана 2021-11-25 в 20 00 51](https://user-images.githubusercontent.com/10318758/143480320-31df5218-66b0-42a0-8ac1-1341d42e41a3.png)
Вполне можем

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/link/Menu.tsx
> +  const data = [
эт надо бы выпилить

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/pages/api/catalog.ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
я кажется видел эти файлы уже в другом реквесте - откуда это тут?

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/pages/link.tsx
> +// страница на период разаработки. Потом удалить
в таких случаях мы заводим задачу и пишем
// TODO: NBPP-XXX

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/components/link/Menu.tsx
> +  enum Appearance {
ничего не понимаю ниже же заэкспорчен енам уже

2021-11-25 17:07 UTC, Snoopyk8411 commented on src/tools/types/api-catalog-items-types.ts
> +  svg?: string;
если это всё же элемент то он HTML, если урл то это svgUrl, если это имя иконки - что наиболее предпочтительно, то это iconName или svgIconName

2021-11-26 06:29 UTC, py-cs requested changes

2021-11-26 06:29 UTC, py-cs commented on src/components/header/header.module.css
> +  margin-right: auto;
padding: 0 10px;
margin: 0 auto;

2021-11-26 06:29 UTC, py-cs commented on src/components/link/Link.tsx
> +  const [style, setStyle] = useState<String>();
useState и useEffect вроде как не нужны, можно же просто из пропсов использовать значение. если условия будут выглядеть перегруженными, то в зависимостях у нас есть classnames, можно её использовать.

2021-11-26 06:29 UTC, py-cs commented on src/components/link/constants.tsx
> +export const highlightStyle = linkStyles.highlight;
Не понял, зачем это вынесено из компонента

2021-11-26 06:29 UTC, py-cs commented on src/components/link/link.module.css
> +  color: var(--red);
рекомендуется в названиях переменных цветов не привязываться к конкретным цветам. если поступит команда заменить основной цвет с красного на зеленый, по всему проекту будут переменные --red со значением #00FF00. лучше использовать primary, accent, brand и т.д.

2021-11-26 06:29 UTC, py-cs commented on src/components/link/link.module.css
> +  color: var(--darkgreen);
тоже нейминг

2021-11-26 06:29 UTC, py-cs commented on src/tools/types/api-catalog-items-types.ts
> +  svg?: string;
Исправлю в своей части.

2021-11-26 06:29 UTC, py-cs commented on styles/globals.css
> +  --darkgreen: rgb(34,139,34);
тоже нейминг

2021-11-26 07:00 UTC, GlebShulga commented on public/assets/pot.svg
> +<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
deleted

2021-11-26 07:01 UTC, GlebShulga commented on public/assets/pot.svg
> +	 viewBox="0 0 35.235 35.235" style="enable-background:new 0 0 35.235 35.235;" xml:space="preserve">
Было в svg. Это свойство уже deprecated. Удалил.

2021-11-26 07:04 UTC, GlebShulga commented on src/components/header/header.module.css
> +  transform: translate3d(0, 0, 0);
Header - это компонент из задачи NBPP-15, тут пока всё 'under contraction'. я её взял пока ждал типы. Нужно было в отдельной ветке начинать её делать.

2021-11-26 07:04 UTC, GlebShulga commented on src/components/header/header.module.css
> +  box-shadow: 0px 1px 17px rgb(0 0 0 / 9%);
Header - это компонент из задачи NBPP-15, тут пока всё 'under contraction'. я её взял пока ждал типы. Нужно было в отдельной ветке начинать её делать.

2021-11-26 07:06 UTC, GlebShulga commented on src/components/link/Link.tsx
> +    if (accent === 1) {
fixed

2021-11-26 08:02 UTC, GlebShulga commented on src/components/link/Link.tsx
> +      {svg && <img src={svg} alt={title} className={linkStyles.svg} />}
Логика в том, что в <img> может приходить любая иконка в зависимости от пути в указанном в пропсах. А <img> за счёт стилей подгонит иконку под нужный размер.

2021-11-26 08:03 UTC, GlebShulga commented on src/pages/api/catalog.ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
Когда делал новую ветку, не проверил и сделал копию с ветки Ивана.

2021-11-26 08:08 UTC, GlebShulga commented on src/components/link/Menu.tsx
> +  enum Appearance {
Весь этот компонент моковый. Я его удалю, как перейду к задаче с хедером.

2021-11-26 08:10 UTC, GlebShulga commented on src/tools/types/api-catalog-items-types.ts
> +  svg?: string;
Делал в соответствии и наименовании в нашей "базе". Исправил на svgUrl

2021-11-26 08:11 UTC, GlebShulga commented on src/components/header/header.module.css
> +  margin-right: auto;
Header - это компонент из задачи NBPP-15, тут пока всё 'under contraction'. я её взял пока ждал типы. Нужно было в отдельной ветке начинать её делать.

2021-11-26 08:26 UTC, GlebShulga commented on src/components/link/constants.tsx
> +export const highlightStyle = linkStyles.highlight;
Переборщил с желанием вынести все константы.

2021-11-26 08:31 UTC, GlebShulga commented on src/components/link/Menu.tsx
> +  const data = [
Весь этот компонент моковый. Я его удалю, как перейду к задаче с хедером.

2021-11-29 13:59 UTC, Snoopyk8411 approved these changes

2021-11-29 15:37 UTC, merged